### ISSUE TITLE
data not copying properly on linux

### ISSUE THREAD

**Issue by anudeepmk** [Azure/azure-storage-fuse#101]
I have mounted blob container on rhel7, I am using cp or mv operations to copy data on the the mounted container, 
Whenever copy data in progress, it creates two directory structures with first letter removed, eg.
if 'catalogsync' is my actual directory, it creates 'atalogsync' and 'catalogsync' both directories, with same directory structure.

please advise on this, as I need to copy huge data(nearly 200G), This goes on creating the directorie(s) fore each directory

**Comment by seguler** [comment]
Ok it sounds like an issue reported last week which we thought we resolved it. The issue was happening when you mount using a tmo-path with trailing slash as such:

Blobfuse /path/to/mount --tmp-path=/my/cache/

Workaround is to drop the trailing slash:

--tmp-path=/my/cache

Can you test and let me know ?

**Comment by seguler** [comment]
Btw - are you sure you are using the latest release ? I have blobfuse 0.2.4 and I couldn't repro this issue. This issue was fixed in 0.2.4: https://github.com/Azure/azure-storage-fuse/releases/tag/v0.2.4

**Comment by anudeepmk** [comment]
it seems be fixed now, I wasnt using the latest one
Thank you so much!

**Comment by seguler** [comment]
Thanks for confirming!
