### ISSUE TITLE
blobfuse2 on AKS 1.25.5 does not support files with `Content-Encoding: gzip`

### ISSUE THREAD

**Issue by eyedvabny** [Azure/azure-storage-fuse#1100]
### Which version of blobfuse was used?
`blobfuse2 version 2.0.1`

### Which OS distribution and version are you using?
AKS 1.25.5 running  `AKSUbuntu-2204gen2containerd-2023.02.15` node image

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
```

### If relevant, please share your mount command.
blobfuse2 mount /var/lib/kubelet/plugins/kubernetes.io/csi/blob.csi.azure.com/40774c1cc34ceb8f8428e46f2de90f65dcd5f007fd997f8fc8e2f8c8ff924f60/globalmount --file-cache-timeout-in-seconds=120 -o negative_timeout=120 --use-attr-cache=true --virtual-directory=true --cache-size-mb=1000 -o allow_other --log-level=LOG_WARNING -o attr_timeout=120 -o entry_timeout=120 --pre-mount-validate=true --use-https=true --cancel-list-on-mount-seconds=10 --empty-dir-check=false --tmp-path=<redacted> --container-name=<redacted> --ignore-open-flags=true

### What was the issue encountered?
blobfuse2 seems to be confused by files which have a Content-Encoding of `gzip`.
<img width="194" alt="image" src="https://user-images.githubusercontent.com/1400408/228942324-dcabb2aa-89ab-4495-bc46-3ca50c8f4e1d.png">

The files show up in the directory just fine, but any attempt to copy or move them results in an IO error:
![image](https://user-images.githubusercontent.com/1400408/228943063-f674f4ba-b52a-4b5e-88de-ccb3a42aac93.png)

This only impacts blobfuse-mounted directories. The file was downloadable from Azure using Storage Explorer and perfectly valid.

### Have you found a mitigation/solution?
Removing or changing Content-Encoding seems to fix the behavior. No value other than `gzip` seems to trigger this issue - we tried `deflate` and `utf-8` and `base64` and even `asdf`. We ended up setting the Content-Type to `application/x-gzip` which is what Azure Storage Explorer sets it to when uploading a gzip file, and not setting Content-Encoding at all.

### Please share logs if available.
Can't find any corresponding to the IO error. `/var/log/blobfuse2` is clear (except not being able to find the du command, which is a known issue on AKS) and there's nothing related to IO in `dmesg`

**Comment by vibhansa-msft** [comment]
As the content encoding is set to 'gzip' the SDK dependency that we have is trying to validate that file has valid 'gzip' headers. If it does not match then it will throw an error. As the file is 'csv' and 'gzip' encoding is set in type its failing. Either you can skip setting this type or use the 'x-gzip' as you have suggested.

**Comment by vibhansa-msft** [comment]
We are looking at this and there is some misunderstanding here.
Can you share why do you need to store the content-encoding type here. Out observation here is if its set to gzip and file is read using browser or curl then data is decoded and delivered to application. However, the content-length reported HTTP headers in this case will still be length of compressed data (stored in container) and actual body reported back will be much larger (as its uncompressed data). This might be the issue we are hitting here. File created based on the content-length will be smaller and we will try to save much larger content in that.

**Comment by eyedvabny** [comment]
There's no requirement for using the Content-Encoding, it just caught us off guard. One of our teams had created the gzipped files with Content-Encoding of `gzip` and Content-Type of `text/csv` expressly for the reasons you described - so that when downloaded through the browser they automatically unpack. But when we tried to serve those same files through a blobfuse-mounted directory, we encountered the IO errors.

We've since switched to using Content-Type of `application/x-gzip` I mentioned when opening the issue. We don't get the auto-gunzip but it works with all of the file delivery methods, including email and blobfuse. I've raised this issue primarily to bring it to your attention since I've not seen Content-Encoding limitations documented anywhere in the repo. Thank you for addressing it so quickly.

**Comment by vibhansa-msft** [comment]
Thanks for clarifying this. We had a debug session yesterday to dig deep into this. By default Accept-Encoding is set to 'true' in HTTP requests that Blobfuse sends. This means if server has done any transport layer compression SDK will decompress and deliver the data back to application. In this case server is not doing any transport layer compression, however as the content-encoding is set on blob, server is forwarding the same in REST response. SDK assumes server has done compression and tries to decompress the data. As compression was not done at transport layer, the content-length that we get for the blob is size of zipped file (x-ms-content-length) and we try to read only that much data from SDK. As SDK went to decompress it, resultant data is of much larger size and this creates a problem in reading and we assume there is some corruption in data. 
One solution to this problem is to disable Accept-Enconding being sent from Blobfuse and assume SDK will never decompress the data as we are asking server not to do any transport layer compression. This will work the way you want, blobfuse not decompressing the data and delivering the zip while browsers decompressing it and delivering original data. As our default blobfuse offering always has encoding set I am adding a new cli parameter using which you can disable this auto decompression feature and running blobfuse with that cli option shall solve your issue.
