### ISSUE TITLE
Blobfuse2 hangs when opening folder containing large files

### ISSUE THREAD

**Issue by pk-rescale** [Azure/azure-storage-fuse#1178]
### Which version of blobfuse was used?
2.0.3

### Which OS distribution and version are you using?
CentOS Linux, on an Azure E-series 4 core machine in South-central US mounting a blob on Azure US East

### If relevant, please share your mount command.
blobfuse2 mount /blob_mount --config-file=config.yaml

YAML config below:
##############################
allow-other: true

logging:
type: syslog
level: log_debug

components:
  - libfuse
  - file_cache
  - attr_cache
  - azstorage

libfuse:
attribute-expiration-sec: 120
entry-expiration-sec: 120
negative-entry-expiration-sec: 240

file_cache:
  path: /tempcache2
  timeout-sec: 120
  max-size-mb: 4096

attr_cache:
timeout-sec: 120
no-cache-on-list: true
no-symlinks: true

azstorage:
max-concurrency: 4
type: block
account-name: XXXXXXXX
container: XXXXXXXXX
endpoint: XXXXXXXX
mode: XXXXXXXXXXX
tenantid: XXXXXXXX
clientid: XXXXXXXXX
clientsecret: XXXXXXXXX
###################################

### What was the issue encountered?
When I interactively (using the Linux file browser in Gnome) open a directory within the blob mount folder that happens to contain some large files, the browser will hang.  It only does this when opening directories containing large (multi-10s of GB size files).  The total number of files in the directory is small, around 20.   Other bad behavior then happens on the machine after the folder hangs, such as all file browsing acting sluggishly. 

Eventually, after a few minutes, the original hanged file browser window will just close -- I can't open it successfully. This only seems to happen in file cache mode, not a stream mode, however I am using file cache mode instead of stream because of other issues I have encountered with stream mode, see:

https://github.com/Azure/azure-storage-fuse/issues/1177

and

https://github.com/Azure/azure-storage-fuse/issues/1141

I don't see the same behavior if I just run an ls command.

### Have you found a mitigation/solution?
No

### Please share logs if available.
Not available

**Comment by pk-rescale** [comment]
Unsure if it is related, but I am also unable to directly update-save a file, interactively in a GUI such as a text editor, to a container mounted with blobfuse2 in filecache mode.  I get the error "Unexpected error: Error renaming temporary file: Input/output error".  The workaround is to save the file somewhere else, delete the old file to be saved over / replaced, and then copy the updated file to the original location.

**Comment by vibhansa-msft** [comment]
In case of file-cache mode, whenever you open a file that particular file will be downloaded entirely into local cache. In such case if the file is large in size, whole operation will be blocked until file is downloaded successfully and this may give an impression on GUI that its sort of hung up. Once file is downloaded it will allow user to do read/write operation.

In second case where it throws rename error, mostly its because of the text editor. Most editors will create a temporary file which will hold your changes until user saves or closes the file. Once user choose to save the file it will rename this temp file to original file and before that remove the original file. If due to some permission issue you do not have rename related permissions in your auth mode, this will just fail. That being said it's an costly operation from customer end if these temp files are created in the same mounted folder. Create a temp file in mounted path means you are copying entire blob to another blob on your storage account by manually uploading the data again (upload cost) which will eventually be renamed, and older blob being deleted. Configure your system to create these temp files in your home / tmp directory and you will see great improvement in performance as well.

**Comment by vibhansa-msft** [comment]
- Blobfuse will not download anyfile unless it gets a kernel call to open a file. When a directory is listed or opened up in GUI, it generally does not trigger any open operation on file (unless your tool/GUI is behaving differently). One way to confirm this is to list the directory and cd to it over console instead of GUI and observe that no file gets downloaded by blobfuse.
- For rename I beleive write and execute permission shall be good enough. Just check with your auth mode (I guess its SPN in your case). You need to provide "storage blob data contributor" role to your SPN or Identity.
- What I meant by the temp files seperation is whatever tool you are using it is creating some temp files in your mount path. These files will be uploaded to container and later they will be deleted (as they were temperory in nature and user application will rename or delete them). If you can configure your GUI/tool/application to create these temp files to some other path that will save some cost for you. For e.g. when you edit any file in vim it creates a temp file (.swp) in the same directory and later when you save the work, original file is deleted and this .swp file is renamed. Vim provides you an option to create these temp files in some other directory.

**Comment by pk-rescale** [comment]
Thanks, I did some checks and it is interesting -- so if I just run an ls command, everything is "normal" (no long delays).  However if I open the folder in the GUI, I get the freeze-up.

**Comment by vibhansa-msft** [comment]
which is what I was suspecting. When you open the GUI may be its trying to check something on each file. For this validation what you need to do is enable debug logs on blobfuse and then open the GUI. Once its frozen go back to logs and see what all operations were called out by GUI. If it tries to open/read files then you will see a lot of open calls in log and this means it will hung up untill the file-downloads are going on.

**Comment by vibhansa-msft** [comment]
This appears to be more of GUI issue then blobfuse. You can always compare the behaviour against the console access and if it works fine from console then blobfuse is not the suspect here.
