### ISSUE TITLE
empty files for subfolders 

### ISSUE THREAD

**Issue by ggrrll** [Azure/azure-storage-fuse#1223]
### Which version of blobfuse was used?
#1222

### Which OS distribution and version are you using?
#1222 

### If relevant, please share your mount command.
#1222 

### What was the issue encountered?
after moving a folder from another disk (XFS partition), many empty files were created with name of sub folders: why? can you prevent that? 

### Have you found a mitigation/solution?
no

**Comment by vibhansa-msft** [comment]
In case of blob account (non-HNS) there is no concept of folders. However, 'blobfuse' being a file-system driver need to represent folders in the containers. To do so we create a blob (file) with 0 byte size and store specific metadata in it to represent it like a folder. If you have empty directories in your folder structure, then you will see such files created in the container. If the folders are not empty then you will see these files and in portal you will see a folder also with the same name (which physically does not exist, it's just in visualization).

This is by design and there is no way to escape this. If your account is HNS enabled then these stubs will not be created.

**Comment by ggrrll** [comment]
ok thanks , I see -- we created a new storage indeed without HNS in order to avoid versioning ... 

RIP folders
