### ISSUE TITLE
Log files are not being creating

### ISSUE THREAD

**Issue by chrisposito** [Azure/azure-storage-fuse#1272]
### Which version of blobfuse was used?
blobfuse2 2.1.0

### Which OS distribution and version are you using?
Ubuntu 22.04.3

### If relevant, please share your mount command.
blobfuse2 mount $mountpoint --container-name=$AZURE_STORAGE_ACCOUNT_CONTAINER --log-level=LOG_DEBUG --tmp-path=$TMP_PATH --allow-other=true

### What was the issue encountered?
Logging does not occur. 
No data is logged to /var/log/syslog. 
No data is logged to "$HOME/.blobfuse2/blobfuse2.log'" 
If I specify a log file path with --log-file-path a file is not created.

### Have you found a mitigation/solution?
No

### Please share logs if available.
Log files are not created.

**Comment by vibhansa-msft** [comment]
Can you check general syslogs are working on your system or not ? If 'rsyslog' is not installed or configured kindly bring it up before mounting blobfuse.
Also, if this is AKS based solution or container based environment, you might need to check your pod/container config as well. I have observed in these solutions logs are not punted to the container/pod's rsyslog rather redirected to some other location where container logs reside.

**Comment by vibhansa-msft** [comment]
syslog not working will not results into blobfuse failure as we do not check whether the service exists or not. In a typical syslog work-flow application just dumps the logs to a pipe and syslog service picks it up from there. So in our case it will just dump it to syslog service and eventually it will go to black-hole if no one picks it up. Can you install the syslog filter that we have and then try again. If filters are there logs shall be in /var/log/blobfuse2.log otherwise it shall be in /var/log/syslog or /var/log/messages only.

**Comment by chrisposito** [comment]
I am seeing these being logged to /var/log/blobfuse2.log and /var/log/blobfuse2-rest.log now after a reboot.
I'm not sure what changed, but it looks like we can close this issue.

**Comment by vibhansa-msft** [comment]
If the syslog service does not restart after installing the blobfuse syslog-filters, you might see this issue.
That is my best guess on why after reboot it started working. However in that case logs should have gone to /var/log/message or /var/log/syslog.
Anyway thanks for confirming that its working for you now.
