### ISSUE TITLE
Failed to close: Input/Output Error

### ISSUE THREAD

**Issue by Subtalime** [Azure/azure-storage-fuse#1278]
### Which version of blobfuse was used?
blobfuse2 version 2.1.1-preview.1

### Which OS distribution and version are you using?
Ubuntu 22.04

### If relevant, please share your mount command.
allow-other: false

logging:
  type: syslog
  level: log_debug

components:
  - libfuse
  - stream
  - attr_cache
  - azstorage

libfuse:
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240

stream:
  block-size-mb: 8
  blocks-per-file: 3
  cache-size-mb: 2048

attr_cache:
  timeout-sec: 30

azstorage:
  type: block
  account-name: <>
  account-key: <>
  endpoint: <>
  mode: key
  container: <>

### What was the issue encountered?
Copying large files (>900MB) with the standard "cp" command from local SSD to Blob-Storage, I constantly receive Input/Output Errors. Smaller files (~200MB) copy fine. I've increased the Cache-Value to 2048 from default 1024. That's about all the changes I did from the default settings.

### Have you found a mitigation/solution?
No

### Please share logs if available.
please find log attached for 1 file

[git-report.log](https://github.com/Azure/azure-storage-fuse/files/13193666/git-report.log)

**Comment by vibhansa-msft** [comment]
Any particular reason to use streaming here ? As file sizes are in MBs only I suggest to rely on file-cache and reason to suggest that is we have been observing some data corruption issue with write mode in streaming which we are already working on.

**Comment by tasherif-msft** [comment]
Hi @Subtalime it looks like the issue is you're using outdated parameters in your config since our samples were not up to date. This caused stream only to be turned on, which means every single write call goes through to storage which can cause blocks to max out and hence larger files failing. I put a pr to fix this https://github.com/Azure/azure-storage-fuse/pull/1292 Please change your config to the new sample and update us if it's still failing.
