### ISSUE TITLE
Not able to Read data from the storage container

### ISSUE THREAD

**Issue by Adarshdynamics** [Azure/azure-storage-fuse#1314]
### Which version of blobfuse was used?

blobfuse2 version 2.1.2
### Which OS distribution and version are you using?

CentOS Stream release 8
### What was the issue encountered?
I am able to list,delete ,write on the mount but not able to read the data from the mount

### Have you found a mitigation/solution?

no
### Please share logs if available.

> blobfuse2 /var/cloudfare_logs/ --tmp-path=/mnt/blobfusetmp

> cd /var/cloudfare_logs
> ls -ltr
total 0
drwxrwxr-x 2 root root 4096 Jan 17 08:21 logs

> cd logs/
> ls 
20240116T040036Z_20240116T040036Z_8b240e68.log.gz

> unzip 20240116T040036Z_20240116T040036Z_8b240e68.log.gz
error:  cannot open zipfile [ 20240116T040036Z_20240116T040036Z_8b240e68.log.gz ]
        Input/output error
unzip:  cannot find or open 20240116T040036Z_20240116T040036Z_8b240e68.log.gz,20240116T040036Z_20240116T040036Z_8b240e68.log.gz.zip or 20240116T040036Z_20240116T040036Z_8b240e68.log.gz.ZIP.

**Comment by souravgupta-msft** [comment]
@Adarshdynamics, can you please share the blobfuse2 debug logs and config file.

**Comment by souravgupta-msft** [comment]
> unzip 20240116T040036Z_20240116T040036Z_8b240e68.log.gz
error: cannot open zipfile [ 20240116T040036Z_20240116T040036Z_8b240e68.log.gz ]
Input/output error
unzip: cannot find or open 20240116T040036Z_20240116T040036Z_8b240e68.log.gz,20240116T040036Z_20240116T040036Z_8b240e68.log.gz.zip or 20240116T040036Z_20240116T040036Z_8b240e68.log.gz.ZIP.

This seems to be a problem with the unzip command. Since, this is not a zip archive, you are getting the above error. In your local file system also, you will get the same error if you run the above command. Please try `gunzip` instead and let me know if it solves the issue.

**Comment by Adarshdynamics** [comment]
I  tried with gunzip too , now after changing the binary to use blobfuse instead of blobfuse2 made it work like a charm. I am able to read,write and process the data too , not sure why the same thing didn;t work with  blobfuse2.

@souravgupta-msft  - Thank you for your input :)

**Comment by souravgupta-msft** [comment]
What error are you getting with gunzip using blobfuse2? Can you please share the debug logs.

I tried the similar use case where I have .gz file in my container and if I use unzip command, I get the same error. But I am not getting any error if use gunzip.

**Comment by Adarshdynamics** [comment]
Oh , my bad I cross-checked and it was again done unzip instead of gunzip :/  . 

Thanks for your quick response!!
