### ISSUE TITLE
Very large number of List operations used

### ISSUE THREAD

**Issue by mfclarke-cnx** [Azure/azure-storage-fuse#1315]
### Which version of blobfuse was used?
I am using the blob.csi.azure.com CSI driver in AKS

### If relevant, please share your mount command.
```
mountOptions:
  - -o allow_other
  - --file-cache-timeout-in-seconds=0
  - --use-attr-cache=true
  - --cancel-list-on-mount-seconds=10  # prevent billing charges on mounting
  - -o attr_timeout=120
```

### What was the issue encountered?
I am seeing millions of List requests being made. The application I am running requires strong consistency for files, so I have disabled the file cache.

### Have you found a mitigation/solution?
Not yet

**Comment by vibhansa-msft** [comment]
If you need strong consistency then you shall disable all sort of caching including attr-cache and any sort of kernel caching as well. For this you also need to use "-o direct_io" flag so that kernel is not caching anything.
Once all caching is disabled, its implicit that there will be higher number of calls to storage. List calls are not just to list the blobs but also to fetch the properties of a given blob. Anytime kernel wants to get the properties  of a file, you will see a list call going to storage with prefix set to the file name.

**Comment by mfclarke-cnx** [comment]
Thank you, that is very insightful. And thanks for the fast response. In that case I think we will have to pivot and use the SDK to interact with the blob store directly.
