### ISSUE TITLE
Upgrade dependency from azure-storage-blob-go to Azure SDK for Go

### ISSUE THREAD

**Issue by IamJeffG** [Azure/azure-storage-fuse#1332]
I was suggested to open this issue here by an Azure Support Engineer (internal case TrackingID#2311160040015094).

### Which version of blobfuse was used?

Not sure, it's running internal to Azure Batch Service.

### Which OS distribution and version are you using?

I've reproduced this on centos 7 and on ubuntu 20.04

### What was the issue encountered?

The background is that I am using Azure Batch service, which internally uses BlobFuse to mount blob storage as virtual volumes in my Docker container.   Sometime between August 28 and August 31, 2023, the stub blobs written by my Batch Tasks via volume mounts on the Batch Pool began using metadata `'Hdi_isfolder=true'` instead of the expected `'hdi_isfolder=true'`  (uppercase 'H').  This breaks [some downstream software that reads these blobs, which is expecting all-lowercase metadata name.](https://github.com/fsspec/adlfs/issues/440)

My expected behavior is that virtual folders written via volume mounts in Batch Tasks use all lowercase metadata, 'hdi_isfolder=true', as it has for years.

### Have you found a mitigation/solution?

The Azure Support Engineer I'm working with writes this:

> The fix for this issue would be to use req.Headers["x-ms-meta-hdi-isfolder"] = []string{"true"] instead of req.Headers.Add("x-ms-meta-hdi_isfolder", "true").
>
> The Azure SDK for GO seems to use the direct key method. However, it appears as if BlobFuse uses the "[github.com/Azure/azure-storage-blob-go](http://github.com/Azure/azure-storage-blob-go)" SDK instead. This SDK uses the older req.Headers.Add(‘key, ‘value’) method instead of the req.Headers[‘key’] = []string(“value”) method.
> 
> We suggest you create a new request in the BlobFuse GitHub as it will be visible to everyone. This will help us track the issue and ensure that it is resolved in a timely manner.

I do notice that Azure SDK for Go once had this issue but it's fixed: https://github.com/Azure/azure-sdk-for-go/issues/17850
I admit that I do not find the place in [azure-storage-blob-go](http://github.com/Azure/azure-storage-blob-go) where this is supposedly creeping in.  At any rate, azure-storage-blob-go is marked as deprecated.

**Comment by milope** [comment]
Adding some context here as I was also reviewing this issue in the background as part of the support incident filed.

**ASK**

The ask is to upgrade BlobFuse from the azure-storage-blob-go to the azure-sdk-for-go.

**MORE CONTEXT**

In operations similar to [Put Blob](https://learn.microsoft.com/rest/api/storageservices/put-blob?tabs=microsoft-entra-id#request-headers-all-blob-types), the `x-ms-meta-*` headers are used to specify metadata key-value pairs to Azure Storage Blobs. In the REST API, it states as follows:

| Request Header | Description |
|-------------------|--------------|
| `x-ms-meta-name:value` | Optional. Name-value pairs associated with the blob as metadata.<br /><br />**Note**: As of version 2009-09-19, metadata names must adhere to the naming rules for [C# identifiers](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference). |

To my remembrance, C# identifiers are case sensitive. However, due to the use of the `req.Headers.Add("key", "value")` in the older 
[azure-storage-blob-go](https://github.com/Azure/azure-storage-blob-go), header names are having their first letter capitalized. For BlobFuse, which its intent is to create a metadata named 'hdi-isfolder' ends up having the metadata stored as 'Hdi-isfolder' which counters the Put Blob's recommendations of following C# identifier specifications. 

The newer [azure-sdk-for-go](https://github.com/Azure/azure-sdk-for-go) appears to use `req.Headers["x-ms-meta-name"] = string[]{"value"}` which doesn't appear to go through the first-letter capitalization, which would also conform with the C# identifier specification. Hence the ask to the BlobFuse team to update dependencies.

**Comment by vibhansa-msft** [comment]
Camel casing of meta names is not something that SDK was doing earlier. API used to push the meta into http header was doing it internally (issue from Golang part). As storage clearly mentions, meta names are to be treated by any application in case-insensitive way, I recommend you do not take any dependency on the casing here. That being said, we are aware of this issue and are already in process of upgrading to Track-2 SDK (azure-sdk-for-go). As this is a major change and will churn a lot of code, it will take some time to complete and stabilize the code. As we are tracking this in our backlog already, I will close this item here.
