### ISSUE TITLE
Blobfuse2 - Libfuse::libfuse_open : Flags (8801) not supported to open xxxx.pdf when write back cache is on. Ignoring unsupported flags.

### ISSUE THREAD

**Issue by Vijay-Raje** [Azure/azure-storage-fuse#1371]
### Which version of blobfuse was used?
blobfuse2-2.1.2-1.x86_64

### Which OS distribution and version are you using?
Rocky Linux release 8.7 (Green Obsidian)

### If relevant, please share your mount command.
blobfuse2 mount /ftp/accountname --allow-other --tmp-path=/mnt/fusetemp --config-file=/etc/blobfuse2/blobfuse_config.yaml

### What was the issue encountered?
seeing below waring logs in blobfuse2 logs file
Libfuse::libfuse_open : Flags (8801) not supported to open xxxx.pdf when write back cache is on. Ignoring unsupported flags.

### Have you found a mitigation/solution?
No

### Please share logs if available.
Fri Mar 22 20:41:18 IST 2024 : blobfuse2[9385] : LOG_WARNING [libfuse_handler.go (684)]: Libfuse::libfuse_open : Flags (8801) not supported to open xxxx.pdf when write back cache is on. Ignoring unsupported flags

**Comment by vibhansa-msft** [comment]
It's just a warning message, is there any error in your operation you are facing?
Just to give some background on this. When write-back cache is enabled kernel does a lot of read operations on the file, even if files is opened in write only mode. To support such cases we open the file always in read-write mode (for perf optimizations). Also, we do not support certain flags due to nature of a network file-system and hence some of the flags provided by user, if not supported, are disabled on the fly. This is normal and you can ignore this warning message unless it's failing some of your file operations.

**Comment by Vijay-Raje** [comment]
Thanks Vibhansa-msft
