### ISSUE TITLE
Caching files from container

### ISSUE THREAD

**Issue by jefjos** [Azure/azure-storage-fuse#193]
I'm reading files from mounted blob container and can see that they are cached locally. These are read-only files and timeout is set to 0. Now to optimize performance should I first check in local cache and if the files not present we must read from the mountpoint. Or does "open" request automatically check the cache for this file and reads from there.

**Comment by seguler** [comment]
If the timeout is set to 0, it will ignore the cached files and will always download the latest blob from Blob storage and open that.

**Comment by seguler** [comment]
So if you call 'open' on a file, 
1) Blobfuse will check the cache folder. Find the file and look at its timestamp and compare whether the following is true ( timeout < current_time - file_timestamp)
2) If true, it will use the cached file
3) If not true, it will download the blob from Blob storage

**Comment by jefjos** [comment]
Thank you. I am running blobfuse command with following options:   blobfuse /home/myuser/temp --tmp-path=/home/myuser/cache/  --config-file=/home/myuser/fuse_connection.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=12 --file-cache-timeout-in-seconds=3600. Now there are no changes to the blob. First run of R script that reads these files(which downloads the files into cache) takes 4 minutes. Second run( which should be reading from cache) also takes 4 minutes.

**Comment by jefjos** [comment]
By reading a file, I mean stack(filename) method from raster package which is used to load geotif files.

**Comment by seguler** [comment]
Interesting. I have just run the exact same blobfuse command to mount, and tested reading 45000 images. I used 'cp' command to read all those. Here are the results:
seguler@seguler-sdk-test:~/temp$ time cp -R images45K /mnt

real    8m28.667s
user    0m0.576s
sys     0m11.355s
seguler@seguler-sdk-test:~/temp$ time cp -R images45K /mnt

real    0m40.544s
user    0m0.340s
sys     0m8.091s


As you see, the second round it completes in 40 seconds when reading from the cache.

Not sure what is going on with your setup. But can you test the performance with 'cp' command ? Also just want to confirm since 4 minutes is also way too long: is your account and VM in the same Azure region ?

**Comment by seguler** [comment]
Ok - unfortunately I do not have an environment to run R scripts, so I am hoping you continue helping me.

First of all, it would be great if you can enable logging and send us the logs from `cat /var/log/syslog | grep blobfuse`

Another thing we can check is the timestamp of the cached files. We simply use the timestamps (ctime - change time, and mtime - modified times) of the cached files to determine whether we download the file from blob storage or not. Here is what we can do:
1. Run the R script once to prime the cache
2. cd /home/myuser/cache/root/**path/to/directory**
3. Then run `stat` on the geotiff file to check its ctime and mtime
4. Run `date` to note down the system's time

How do these look ? If ctime and mtime together is 60 minutes older than the current time, then blobfuse will download a new file from Blob storage. When blobfuse downloads it again, the ctime will be updated, and the file will be used for another 60 minutes.

Hope we can get to the bottom of this!

**Comment by jefjos** [comment]
`root@msclimateCPU:/home/jeffy/cache/root# stat 060c9ef9-c46f-11e5-b83e-22000bb78209_2017.tif
  File: '060c9ef9-c46f-11e5-b83e-22000bb78209_2017.tif'
  Size: 128350          Blocks: 256        IO Block: 4096   regular file
Device: 801h/2049d      Inode: 4102209     Links: 1
Access: (0777/-rwxrwxrwx)  Uid: ( 1002/   jeffy)   Gid: ( 1002/   jeffy)
Access: 2018-07-02 09:05:28.465061642 +0000
Modify: 2018-06-14 15:15:33.000000000 +0000
Change: 2018-07-02 09:05:28.781058500 +0000
 Birth: -
root@msclimateCPU:/home/jeffy/cache/root# date
Mon Jul  2 09:16:47 UTC 2018
`

**Comment by jefjos** [comment]
Blobfuse logs
```
Jul  2 09:02:43 msclimateCPU kernel: [515464.163906] [75980]     0 75980    85167      827   262144        0             0 blobfuse
Jul  2 09:02:43 msclimateCPU kernel: [515464.163908] [75987]     0 75987    85133     1957   274432        0             0 blobfuse
Jul  2 09:02:43 msclimateCPU kernel: [515464.163929] [83075]  1002 83075   119950     9275   438272        0             0 blobfuse

```

**Comment by seguler** [comment]
Based on the timestamps you've provided above, blobfuse definitely will reuse the cached file, but somehow reading the cached file seems to be slow. This may be because R script uses very low IO sizes when accessing the file as opposed to `cp` tool uses. 


One thing I see is that you use a home directory for caching files. Is this VM in Azure ? If so, it could be that your OS disk is a low-sku, low-throughput disk. Can you instead move the cache disk to the ephemeral SSD or ramdisk ? Ephemeral SSD in Azure is the /mnt/resource directory. Maybe this can make a difference.

**Comment by seguler** [comment]
Also the logs does not seem to be on based on what you've provided. Have you mounted blobfuse with option `--log-level=LOG_DEBUG` ?

**Comment by seguler** [comment]
closing as no response
