### ISSUE TITLE
Failed to download blob into cache

### ISSUE THREAD

**Issue by vijayraje23** [Azure/azure-storage-fuse#209]
### Which version of the blobfuse was used?
blobfuse-1.0.2-1

### Which OS (please include version) are you using?
CentOS Linux release 7.5.1804 (Core)

### What problem was encountered?
Getting below error in /var/log/message file for temp blob.
Aug 20 14:36:46 azblobftp02 blobfuse[1193]: get_chunk_to_stream_async failed for firstchunk in download_blob_to_file.  container = blobftp, blob = user01/mobiledoc/up224.txt, destPath = /mnt/blobfusetmp/root/user01/mobiledoc/up224.txt.

Aug 20 14:36:46 azblobftp02 blobfuse[1193]: Failed to download blob into cache.  Blob name: user01/mobiledoc/up224.txt, file name = /mnt/blobfusetmp/root/user01/mobiledoc/up224.txt, storage errno = 1600.

### Have you found a mitigation/solution?
No

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
No

### If relevant, please share your mount command.

blobfuse /ftp/localuser --tmp-path=/mnt/blobfusetmp --config-file=/etc/vsftpd/connection.cfg  -o allow_other -o nonempty

**Comment by seguler** [comment]
Do you have space in your temp directory ? `df -k` and check the /mnt partition

Also are you able to create new files in /mnt/blobfusetmp with your user ? Try `touch /mnt/blobfusetmp/test`

Did it every work ? If it did, most probably your issue is the disk space. If it did not, it could be permission issue

**Comment by vijayraje23** [comment]
Yes, We have enough free space on /mnt and able to create new files. There is now issue with permission as well. Sometime its working fine and sometime not.

**Comment by seguler** [comment]
Ok - this is not a known issue, and never been reported before. Can you give us more details, or tell us how to reproduce ?

- Where is your VM ? 
- What type of VM is it ? How many cores ?
- How far is the VM from the Storage account ?
- Can you test this on a CentOS 7.3 or earlier ? I don't recall getting this tested on 7.5.
- How do you download the file ? Are you using CP command ?
- You said it sometimes work. When does it work, when does it not ? When you copy multiple files, does any file copy work ?
- How big is the file you are downloading ? Do you have that much space in the /mnt partition ? If the file is 100GB, you need at least 100GB in the /mnt partition
- Why do you need to use -o nonempty flag ? Not sure what it is for. Does it work without that ?
- Can you set the log level to LOG_DEBUG ? --log-level=LOG_DEBUG

**Comment by vijayraje23** [comment]
There was typo on above reply. There is no issue with permission as well. We deployed new VM and configured VSFTPD and blobfuse. Its working fine now. 

I did the same installation and configuration steps on both servers(older and new).so can you help me what could be the issue.

**Comment by seguler** [comment]
Have you fixed your first VM ? If not, help me understand the issue by responding to the previous questions

**Comment by yangsiyu007** [comment]
Hi @seguler, I also encountered the error "Failed to download blob into cache.  Blob name: x.zip, storage errno = 1600." (from syslog) as I was running a script copying zip files from a mounted blob container to a local disk. Checking disk space using `df -k`, it shows that 
`blobfuse         50758760  46418484    4323892  92% /home/yasiyu/mnt/containername`
which makes sense since any blob with size above about 4GB are failing to get copied / downloaded to cache. 

How do I mitigate this? Since I don't need the rest of the files currently in cache, can I clear them? Or is it because I didn't close them properly?

**Comment by seguler** [comment]
Ok - files would be automatically deleted after the cache timeout. By default it is set to 120 seconds... So, since the files will be around for 120 seconds, your script should not access files that are larger than your cache space can handle during this 120 seconds... E.g. if you are opening 1TB of data in 120 seconds, you need 1TB cache space.

Alternatively you can reduce the cache timeout to 0 (`--file-cache-timeout-in-seconds=0`). So any file that is closed will be immediately removed from the cache space.

**Comment by ludlbn** [comment]
Hello @seguler, I have similar issue.

Sometimes we got issues Failed to download blob into cache for a specific file, with storage errno = 1600.
`--file-cache-timeout-in-seconds` is configured by default (120sec).

We using azure temporary disk mount in /mnt/resources to cache blob data. Actually, it size of Azure temp disk is 64Go.
Our Azure blob storage has 40Go used space, but in in mount cache we using only 2.5Go (average).

have you already get this type of issues ?*
thanks.

**Comment by vibhansa-msft** [comment]
Hi @ludlbn 
Is this issue still seen. As per your last comments, there was some sort of exception or crash during the download. Can you give latest version a try, quite a few crash and bug fixes have gone in since the version which was discussed in this thread.

**Comment by vibhansa-msft** [comment]
Closing as no response received from submitter. Reopen if issue persists.
