### ISSUE TITLE
Blobfuse install on Ubuntu 17.10 not working

### ISSUE THREAD

**Issue by cburko** [Azure/azure-storage-fuse#215]
### Which version of the blobfuse was used?
Blobfuse 1.0.2
fuse is already the newest version (2.9.7-1ubuntu1).

### Which OS (please include version) are you using?
Ubuntu 17.10

### What problem was encountered?
After installing blobfuse I get the following message when I run 'blobfuse'

blobfuse: error while loading shared libraries: libgnutls.so.26: cannot open shared object file: No such file or directory

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
Nothing found in /var/log/syslog

I run the following to install:
sudo wget https://packages.microsoft.com/config/ubuntu/17.10/packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
sudo apt-get update
sudo apt-get install blobfuse fuse

There are no errors on install. I’ve installed pre-requisites below – it looks like there’s a newer version of libgnutls included – perhaps this is interfering?

sudo apt-get install pkg-config libfuse-dev cmake libcurl4-gnutls-dev libgnutls28-dev uuid-dev libgcrypt20-dev -y

Any ideas on why I can't run blobfuse on Ubuntu 17.10?

Many thanks
Chris

**Comment by carlosporter** [comment]
Hello,
Can you add an example of the command you're using to mount the storage container?

Can you can you verify what version of blob fuse do you have installed?

Also, I followed your steps and I got a different version installed:

user@workstation:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 17.10
Release:        17.10
Codename:       artful
user@workstation:~$

user@workstation:~$ dpkg-query -s blobfuse
Package: blobfuse
Status: install ok installed
Priority: optional
Section: devel
Installed-Size: 14271
Maintainer: Microsoft - Azure Storage
Architecture: amd64
Version: 1.0.1-RC-preview
Depends: libc6 (>= 2.14), libcurl3-gnutls (>= 7.16.2), libfuse2 (>= 2.8), libgcc1 (>= 1:3.0), libgcrypt20 (>= 1.7.0), libgnutls30 (>= 3.5.0), libstdc++6 (>= 7), libuuid1 (>= 2.16)
Description: FUSE adapter for Azure Blob Storage - MIT License
Homepage: https://github.com/azure/azure-storage-fuse
user@workstation:~$

**Comment by seguler** [comment]
Ubuntu 17.10 was end of life in June. Hence we did not deliver the stable version of the blobfuse. Please upgrade to 18.04.

**Comment by cburko** [comment]
Thanks everyone - this was for a one off file copy to blob - I've used AzCopy in the interim which has worked well. We're using 18.04 for all other workloads so I'm happy that this won't be required in future.

**Comment by flybd5** [comment]
> Ubuntu 17.10 was end of life in June. Hence we did not deliver the stable version of the blobfuse. Please upgrade to 18.04.

Umm... this is a joke, right? Azure supports a lot more than 18.04, and for very good reasons. In fact you can request a VM to be provisioned all the way back to 12.04.3-LTS. Who exactly made this dumb business decision to cutoff support for Blobfuse at 18.04 for "end of life" reasons that have nothing to do with Microsoft or Azure?

There are customers who are transferring services to Azure that are based on older versions of Ubuntu and other operating systems. One of my customers is an example of that, they are doing lift-and-shift of their legacy product for a ton of customers to reduce costs while they reengineer their app for deployment using Kubernetes. They have no intention whatsoever of injecting a high level of risk by upgrading the OS on a service 99% of their customers are still using.

This "decision" of yours kills their ability to use storage containers and blobs to manage a ton of data -- and directly affects Azure's bottom line, because the customer doesn't care about your excuses. If the OS is supported as a VM and you won't support it with this tool, it is useless, and they will look elsewhere for services. 

So, what was it you said about telling people they should upgrade???
