### ISSUE TITLE
Optimize scenario where the file is open for read/write, but no actual writing occurs, to not upload the blob

### ISSUE THREAD

**Issue by SkinyMonkey** [Azure/azure-storage-fuse#217]
Hi! I stumbled upon this line:

// TODO: Optimize the scenario where the file is open for read/write, but no actual writing occurs, to not upload the blob.

That I could be interested in implementing.
Would it take a lot of changes?

If not I would happily do a PR for this :)

**Comment by seguler** [comment]
Yes PRs are appreciated! But read on before you send the PR. This was a little complex issue hence we left it unfixed.

So, every open file has a filehandle stored in fhwrapper struct here: https://github.com/Azure/azure-storage-fuse/blob/43e82df5d85a4c082dc67af8131bcf05f4d9270a/blobfuse/blobfuse.h#L99

This handle includes a bool `upload` parameter, to store whether the file needs to be uploaded to Blob storage. 

Unfortunately we set this to true in azs_open if the file was either opened with 'rw' or 'w' flags. Because of this we upload all files to Blob storage even if they were opened with 'rw' but were never written to. https://github.com/Azure/azure-storage-fuse/blob/master/blobfuse/fileapis.cpp#L166

Instead this bool `upload` should be updated within the azs_write function. Azs_write is what's called by the FUSE library whenever there is a write. But this function is called too many times (once every 4KB-128KB), hence updating the struct in each azs_write will probably be done in a thread safe way, and will impact the write performance. 

It would be great if you could look into ways to solve this problem in a performance efficient and thread safe way. There will be lot of concurrency tests to be done to see whether the fix has any race conditions.

Good luck!

**Comment by SkinyMonkey** [comment]
Hi!

Sorry but my company choose another solution than azure-storage-fuse.

Maybe this explanation will help someone else do it :)

**Comment by seguler** [comment]
Thanks @SkinyMoney - May I ask what was the solution you ended up with ? Was the reason because of the inefficiency in blobfuse for uploading the data ?

**Comment by SkinyMonkey** [comment]
As we're working with kubernetes we ended using the Azure external provisioner.
This allow us to share the volume between the successive container we use and avoid redownloading the files on each node that runs them (as would do azure blob and its cache).

Overall the experience with blobfuse was really good, we just found a more efficient way to work in our case :)
