### ISSUE TITLE
How to configue storage emulator account

### ISSUE THREAD

**Issue by Spaceman1861** [Azure/azure-storage-fuse#218]
### Which version of the blobfuse was used?
1.0.2

### Which OS (please include version) are you using?
CentOs 7

### What problem was encountered?
I am attempting to connect to my local storage emulator via my docker container. I believe i'm getting the same symptoms as https://github.com/Azure/azure-storage-fuse/issues/194 I fire and it stalls.

### Have you found a mitigation/solution?
Nope

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
Logs are empty

### If relevant, please share your mount command.
`blobfuse /usr/share/elasticsearch/data --tmp-path=/mnt/resource/blobfusetmp --config-file=connection.cfg --log-level=LOG_DEBUG
`
**Config settings**
`tail -10 connection.cfg  `
Resolves as:
```
accountName devstoreaccount1
accountKey Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
containerName test
blobEndpoint host.docker.internal:10000
```

**Comment by seguler** [comment]
Do you use Azurite for the emulator ? What is the use case for this ? I'd be interested in learning more about what you're trying to do.

**Comment by Spaceman1861** [comment]
@seguler 
Hey mate,

Im using this emulator.
https://docs.microsoft.com/en-us/azure/storage/common/storage-use-emulator

Not sure what azurite is.

The use case is fairly hacky.

We have an docker container that fires a blob storage connection as apart of the entrypoint.
It looks then copies some files over and starts an application.

Periodically the application it writes files to the blob storage.

This is working fine for our live and staging environments but testing locally we cannot configure it.

**Comment by seguler** [comment]
Ok - it could be something to do with the Azure Storage Emulator. Try Azurite instead which is Linux compatible: https://github.com/azure/Azurite  I am hoping this will resolve your issue

**Comment by stephenllai** [comment]
To my understanding, the problem is caused by different URI for addressing resources in the storage emulator.

For addressing a resource in an Azure storage account, the URI is
<http | https>://<account-name>.<service-name>.core.windows.net/<resource-path>

On the other hand, for addressing a resource in a storage emulator, the URI is
http://<local-machine-address>:<port>/<account-name>/<resource-path>
where
for Blob service, the port is 10000
for Queue service, the port is 10001
for Table service, the port is 10002

When blobfuse is being configured, it accepts only the account name, and construct the URI using the pattern for Azure storage account.

Unless blobfuse allows us to provide the URI (therefore, we can construct the URI by ourselves using the pattern for a storage emulator), I don't think blobfuse can be used with a storage emulator.

**Comment by Spaceman1861** [comment]
I had stepped around this issue by just testing against a separate storage account. 

It would be preferable thought to use the local storage.

To clarify im running the storage emulator on my windows box.

The windows box is hosting a docker image running cent os.

The docker image is attempting to access the blob storage on the windows box.

So using the linux emulator will not help me. :)

**Comment by gapra-msft** [comment]
Hi all,

We are working on next generation of blobfuse called "blobfuse2" (in preview mode as of now) **that [supports ](https://github.com/Azure/azure-storage-fuse/pull/865)Azurite style endpoints.** If you wish you give it a try, you can get the binary from this link : https://github.com/Azure/azure-storage-fuse/releases/tag/blobfuse2-2.0.0-preview2 or install it from the Microsoft repos (package name is blobfuse2)
Blobfuse2 has a different cli and config model so you can refer to our readme @ https://github.com/Azure/azure-storage-fuse/tree/main#readme
