### ISSUE TITLE
Memory usage is getting higher

### ISSUE THREAD

**Issue by taoyama** [Azure/azure-storage-fuse#246]
### Which version of the blobfuse was used?
1.0.2

### Which OS (please include version) are you using?
Red Hat Enterprise Linux Server release 7.5 (Maipo)

### What problem was encountered?
Memory usage of blobfuse process is getting higher.
When I look into memory map (/proc/pid/maps), I can see anonymous memory region is getting bigger.
It could be a memory leak.
I also checked the memory content in these address by debugger. It looks like the address contains pointer or something...

### Have you found a mitigation/solution?
Restart the process

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
No

**Comment by amnguye** [comment]
@vyelamanchili 
I don't have an idea what version of blobfuse you're using and how you're using it. So you know you are overloading the memory usage on it?

I would apperciate it if you started a new issue for your situation.

**Comment by vyelamanchili** [comment]
> @vyelamanchili
> I don't have an idea what version of blobfuse you're using and how you're using it. So you know you are overloading the memory usage on it?
> 
> I would apperciate it if you started a new issue for your situation.

Version is 1.0.3 and I dont know if I am overloading memory but wanted to know the how to auto remount blobfuse if it gets unmounted for ANY reason. If its not a short answer like pointing me to a link somewhere for documentation then I will create a new issue.

**Comment by amnguye** [comment]
There's no short answer. There's no option for automatically remounting blobfuse after it gets unmounted for any reason. If it's getting unmounted randomly, I will suspect it is running out of memory for how much you've allocated to it. If you upgrade blobfuse, we've upgraded the caching scheme to automatically reduce the files in the cache when it reaches a certain threshold and will reduce once it gets below a lower threshold. 

This issue is from January. It's easy to lose this conversation if you comment on an old issue, but if you want to stay on this thread that's up to you. Please fill out the form if you do make a new issue that way we can more easily figure out what the problem is and the environment you have blobfuse running in.

**Comment by NaraVen** [comment]
We recommend larger VMs for large blobs to circumvent this issue. Since we cache touch files and limit it to 80% of the available memory, this issue is currently unavoidable. I do recommend you upgrade to the latest version 1.2.3. Due to the optimizations the frequency of this happening will be a lot lower.

**Comment by JWT95** [comment]
> We have a known issue where we keep a memory map of all the files you view and touch through blobfuse, which never gets purged. Map grows without a bound.

Is this still the case?

**Comment by NaraVen** [comment]
> > We have a known issue where we keep a memory map of all the files you view and touch through blobfuse, which never gets purged. Map grows without a bound.
> 
> Is this still the case?

No not at all. Please upgrade to 1.3.7

**Comment by vibhansa-msft** [comment]
Blobfuse does keep a file being touched in local cache. However memory usage has been optimized in our recent releases. Kindly try out our latest version 1.3.7.

**Comment by JWT95** [comment]
Thanks!

Another question on memory. Does the parameter --cache-size-mb=1000 refer to memory used by the blobfuse process or refer to the disk space used for the file cache?

If memory, then would there be a big impact to dropping it to say 100MB?

**Comment by vibhansa-msft** [comment]
Its the disk space used for file-cache.

**Comment by JWT95** [comment]
Thanks!

Is there any way to reduce memory usage by blobfuse? On my test system it's at 1GB RAM even when the file-cache is empty and having written ~100 large files to Blob Storage since the process was started.

**Comment by vibhansa-msft** [comment]
There is no way to control/reduce the memory usage of the process as such.
