### ISSUE TITLE
Don't mount Archive tier/don't allow reads for Archive

### ISSUE THREAD

**Issue by rigdent** [Azure/azure-storage-fuse#257]
Hello,

Is there a way to **NOT** mount or disallow reads for files that are in Archive storage tier? The costs to access Archive stored files are so high that I don't want to allow accidental reads of them.

Thank you.

**Comment by seguler** [comment]
I don't think trying to read an archived blob costs you anything. It will throw a failure. When you change the tier of an archived file to hot or cool tier costs you something. I'll confirm this with my colleagues and update this issue.

**Comment by ivanignatiev** [comment]
At least, is there is a way to hide archived documents?

It is not an issue of cost but there is some confusion. When I am on server, I am able to edit and see edits in files which were moved to Archive.  I suppose, if I ask to rehydrate the file, I will lost all changes which I have done locally.

So, the danger here that there is no any difference between Archived and non-Archived files when we are looking on them at file system level.

**Comment by amnguye** [comment]
There isn't a way to ignore archived documents.

What do you mean that when you're on the server, do you mean when you're running blobfuse? If it's through blobfuse, do you archive the files using a different process or client to do so? That's probably why you can still see it using blobfuse because blobfuse doesn't know other processes accessing the blobs.

**Comment by ivanignatiev** [comment]
@amnguye Thank you for clarification !

Exactly I was archiving the document from Azure Portal. I understand now that If I did something from other process I need to remount blobfuse to clear the cache to avoid any confusions.
