### ISSUE TITLE
File operation command hangs on network failure.

### ISSUE THREAD

**Issue by taoyama** [Azure/azure-storage-fuse#261]
### Which version of the blobfuse was used?
1.0.2

### Which OS (please include version) are you using?
RHEL7.x

### What problem was encountered?
File operation command hangs.

### Have you found a mitigation/solution?
Reboot the VM.
Kill -KILL did not work. I believe that is because it was stuck in linux kernel.

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
NO.

### If relevant, please share your mount command.
Here is the bt of the core.

Core was generated by `ls'.
#0  0x00007ff7f34c1855 in __getdents64 () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install coreutils-8.22-23.el7.x86_64
(gdb) bt
#0  0x00007ff7f34c1855 in __getdents64 () from /lib64/libc.so.6
#1  0x00007ff7f34c1451 in readdir64 () from /lib64/libc.so.6
#2  0x0000000000408fa0 in print_dir ()
#3  0x0000000000402e1d in main ()

You can easily repro this problem.
1. mount blobfuse
2. block network access by NSG
3. ls in mounted directory

**Comment by seguler** [comment]
Thanks @Taoyama - this is per design. Blobfuse does not hang, but it just keeps retrying (20 times backing off exponentially) until it reaches network. This is so that there is minimal possibility that there is data loss in case of a network issue... But turns out this behavior make blobfuse look like it is hung. Therefore I agree that this needs to be changed. At least after 30-60 seconds, blobfuse should time out and return an error. Does this make sense ?

**Comment by taoyama** [comment]
Thanks for the detail. This is making a sense.
It is preferable to have a mount option which is similar to "soft" option for NFS/CIFS.

**Comment by amnguye** [comment]
We are actually looking into this to limit the amount of retries it has. This issue already exists

https://github.com/Azure/azure-storage-fuse/issues/221
