### ISSUE TITLE
Can't persistent mount following wiki instructions

### ISSUE THREAD

**Issue by rbavery** [Azure/azure-storage-fuse#269]
### Which version of the blobfuse was used?
1.0.3

### Which OS (please include version) are you using?
Virtualization: microsoft
Operating System: Ubuntu 16.04.5 LTS
Kernel: Linux 4.15.0-1041-azure
Architecture: x86-64

### What problem was encountered?
I followed the wiki instructions to get persistent storage working after discovering that the one-time mount was not preserved after stopping my vm. I then was unable to ssh into my vm after editing my fstab file and found in the Serial Console that the mount was failing.

I am using the Microsoft Data Science VM which had blobfuse 1.0.2 installed and did not have fuse. I installed both with apt-get. So I didn't build from source and thus didn't use the mount.sh script but I took a look at it to see what I should add to fstab. Following the wiki suggestion of 

```
/<path_to_blobfuse>/mount.sh </path/to/desired/mountpoint> fuse _netdev
```

Here is what I added that caused the vm to fail starting properly:

```
# mounts the blob container at az-ml-container
blobfuse /az-ml-container --tmp-path=/mnt/blobfusetmp -o big_writes -o max_read=131072 -o max_write=131072 -o attr_timeout=240 -o fsname=blobfuse -o entry_timeout=240 -o negative_timeout=120 --config-file=/opt/blobfuse.cfg fuse _netdev
```

`/az-ml-container` is the path to where I want the container mounted. I ran the `chown` step for both `/mnt/blobfusetmp` and `/az-ml-container`. I thought that `fuse _netdev would need to be added to the end like it is for the example in the wiki that uses `mount.sh` but something is wrong here.

### Have you found a mitigation/solution?
No

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?

I took some screenshots of the errors as they appeared in the Serial Console
![Selection_584](https://user-images.githubusercontent.com/22258697/56465540-07584800-63b4-11e9-85d6-74f46eecdc16.png)
![Selection_583](https://user-images.githubusercontent.com/22258697/56465541-07584800-63b4-11e9-831a-c854208bfd5d.png)

None of the errors were captured in the log file, these errors are old and happened before I tried to restart the vm after editing the fstab
```
319:Apr 19 18:47:07 cropmask-dev systemd[1]: Unmounting /mnt...
482:Apr 19 21:50:14 cropmask-dev systemd[1]: Unmounted /mnt.
1002:Apr 19 21:50:14 cropmask-dev systemd[1]: Mounting /mnt...
1020:Apr 19 21:50:14 cropmask-dev systemd[1]: Mounted /mnt.
1245:Apr 19 21:50:16 cropmask-dev root: Added ephemeral disk warning to /mnt/DATALOSS_WARNING_README.txt
1692:Apr 21 01:14:56 cropmask-dev systemd[1]: Unmounted /mnt.
1730:Apr 21 01:14:56 cropmask-dev systemd[1]: Mounting /mnt...
1952:Apr 21 01:14:56 cropmask-dev systemd[1]: Mounted /mnt.
2459:Apr 21 01:15:00 cropmask-dev root: Added ephemeral disk warning to /mnt/DATALOSS_WARNING_README.txt
2739:Apr 21 01:27:35 cropmask-dev blobfuse[4780]: Unable to start blobfuse.  Failed to create directory on cache directory: /mnt/blobfusecache/root/placeholder, errno = 13.
2747:Apr 21 01:30:39 cropmask-dev blobfuse[5000]: Unable to start blobfuse.  Failed to create directory on cache directory: /mnt/blobfusecache/root/placeholder, errno = 13.
2748:Apr 21 01:33:10 cropmask-dev blobfuse[5133]: Unable to start blobfuse.  Failed to create directory on cache directory: /mnt/blobfusecache/root/placeholder, errno = 13.
2751:Apr 21 01:36:59 cropmask-dev blobfuse[5353]: Unable to start blobfuse.  Failed to create directory on cache directory: /mnt/blobfusecache/root/placeholder, errno = 13.
2796:Apr 21 02:29:25 cropmask-dev systemd[1]: Unmounting /mnt...

```

### If relevant, please share your mount command.
This one time mount command works

```
blobfuse /az-ml-container --tmp-path=/mnt/blobfusetmp -o big_writes -o max_read=131072 -o max_write=131072 -o attr_timeout=240 -o fsname=blobfuse -o entry_timeout=240 -o negative_timeout=120 --config-file=/opt/blobfuse.cfg
```

**Comment by rbavery** [comment]
Also, I'm unsure if this is realted, but when I try to one-time mount again after deallocating and starting my VM again, I can't seem to get chown to work.

```
(base) ryan@cropmask-dev:~$ sudo chown -R ryan /az-ml-container
(base) ryan@cropmask-dev:~$ ls /az-ml-container 
ls: cannot access '/az-ml-container': Permission denied
```
I can still one-time mount the container however using the above mount command.

**Comment by rbavery** [comment]
And I can't unmount the mount point as suggested int he wiki

```
(base) ryan@cropmask-dev:~$ fusermount -u /az-ml-container
fusermount: entry for /az-ml-container not found in /etc/mtab
```
Any help is appreciated!

**Comment by amnguye** [comment]
Sorry for the delay in response.

So from my understanding, is that you have your vm running and blobfuse running and then after stopping your vm and starting your vm up again, blobfuse isn't running still? I think that's by design that if you stop your vm from running, blobfuse is unable to run as well because blobfuse is a process still. Also by stopping the vm you prevent network access which stops the mounted container/blobfuse from being able to access the network.

Could you include the contents of your /etc/fstab. You can replace certain values with <inserts> in order to persevere privacy.

With having a folder at root, I think it would be difficult to give your user access to it. You might have to put it in the /mnt folder for a better chance of giving your user permissions to the folder. You might have to edit your fstab file to add your user to to allow permissions to a root folder. Usually linux kernels prevents users from getting to access to those folders close to the root directory.

In the problem of not being able to mount, I'm surprised blobfuse let you mount the container in the first place if you didn't have access or permissions in the first place. That error message is an indication that the filesystem isn't mounted. Could you use the "df" command to ensure that the container is mounted in the first place? You can also try "df -h" as well.
