### ISSUE TITLE
zero bytes block blob

### ISSUE THREAD

**Issue by cometta** [Azure/azure-storage-fuse#280]
### Which version of the blobfuse was used?
latest version

### Which OS (please include version) are you using?
linux

### What problem was encountered?
when I ran cp -rf /local/directory to /azure/mounted/ , the folders and files were copied over to the azure. However, I can also see additional files with same name with zero bytes. Is this the default behavior? My storage account settings are like below

Standard
Locally-redundant storage (LRS)
Storage (general purpose v1)

**Comment by amnguye** [comment]
Hi Cometta,
That is by design when you upload directories.
So I'm assuming what you're seeing is say you have /azure/mounted/exampledir1 and /azure/mounted/exampledir1/exampledir2/
and then when you look in your azure portal, you see

> /exampledir1 (as a folder)
> exampledir1 (0 byte block blob)

and click into your /exampledir1 directory you probably see
..
file1
file2
exampledir2 (0 byte block blob)

I hope this helps.
