### ISSUE TITLE
Processes indefinitely waiting for blobfuse

### ISSUE THREAD

**Issue by JelleVE** [Azure/azure-storage-fuse#292]
### Which version of the blobfuse was used?
blobfuse 1.03

### Which OS (please include version) are you using?
Ubuntu 18.04

### What problem was encountered?
I am processing a large number of files through blobfuse. For this, I have a Python script that spawns multiple (8) processes.  Typically, the script will work as intended for quite some time with a throughput of about 1 file per second. Often, the throughput will decrease after a while and a number of Python processes will enter a perpetual sleep state, waiting for blobfuse (or so I assume). From time to time all the Python process will end up in such an indefinite sleep state.

Any ideas as to what might be the issue? Thanks!

### Have you found a mitigation/solution?
No

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
Nothing blobfuse related

**Comment by amnguye** [comment]
If the script is going through a file per second, maybe you have to set the "--file-cache-timeout-in-seconds" to a lower number. I think maybe the cache is filling up too quickly? I'm honestly not to sure of the settings of your mount command because you didn't provide it. You might also want to use the "--log-level=LOG_DEBUG" to see what blobfuse is doing at the moment or what it could be doing.

I'm going to need more details in order to know what's going on and to help you with this issue.

**Comment by JelleVE** [comment]
Resolved, thank you for your help!
