### ISSUE TITLE
Reported disk size

### ISSUE THREAD

**Issue by bouman21** [Azure/azure-storage-fuse#293]
Hi,

Related to #96, I have a tool that requires a disk of at least 500GB in total size. 

The local disk the cache is mounted on is much less and as such the disk space reported is too little. There is no need to store files larger than cache size though. Is there a way to work around this?

**Comment by amnguye** [comment]
Hi,

So how much space do you have allocated to your cache container? What's the biggest file you are opening? Blobfuse opens an entire file and caches it, when you call open. Also if you are opening multiple files at once more space will be allocated to cache this.

Also I recommend if you don't have that much space to allocate for your cache, you might want to reduce the amount for your "“--file-cache-timeout-in-seconds=" flag. That way the cache is cleaned more often since your cahce is not that big.

Also I was wonder how big is the RAM disk size you have. Unless you mean your RAM disk is 500gb.

**Comment by bouman21** [comment]
Hi,

The disk the cache container is mounted on, is 40GB. The largest file that will be opened is 100MB, so that should be enough for operational use. It will just store a lot of data that could be requested (but not all at once ...). I will amend the cache timeout setting, that seems like a good change!
I'm not sure where the RAM disk comes in play, there is no RAM disk afaik.

Right now when the software queries the size, it requires a total of at least 500GB (which is no issue on blob storage) but the returned value is much less.
F.e. DAVFS returns the size of the connected share, not the local space available, that works well.

**Comment by amnguye** [comment]
Hi,

I also forgot to ask this, but what's the size of the cache tmp folder you have allocated for blobfuse. So this is different from the directory you have mounted for your container.

Also what linux distro os and version are you working off of right now? Also what's your mount command?

**Comment by NaraVen** [comment]
@bouman21, if your largest file is only 200MB , and if you set --file-cache-timeout-in-seconds=0 you should be able to do with a temp disk of 5 GB or less. you say you have 40 GB for blobfuse so this should work. If it does could you please send us the output of your df -k and reopen this issue.
