### ISSUE TITLE
blobfuse invoked oom-killer

### ISSUE THREAD

**Issue by yderi** [Azure/azure-storage-fuse#295]
### Which version of the blobfuse was used?
blobfuse 1.0.3

### Which OS (please include version) are you using?
Ubuntu 16.04.6 LTS
Linux hp 4.4.0-157-generic 

### What problem was encountered?
blobfuse invoked oom-killer

### Have you found a mitigation/solution?
No, just reboot a system to get it fixed.

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?

[syslog.OOM_Killer_log.zip](https://github.com/Azure/azure-storage-fuse/files/3446149/syslog.OOM_Killer_log.zip)

#### Here is the part of mine fstab:
```
# tmpfs for blobfuse
tmpfs /mnt/ramdisk tmpfs rw,relatime,size=1700M 0 0

# mount for blob storage
/etc/blobmount.sh /home/ubuntu/blobvideo fuse _netdev
```
#### Here is the body for "blobmount.sh" script:
```
#!/bin/bash
blobfuse $1 --tmp-path=/mnt/ramdisk/blobfusetmp   --file-cache-timeout-in-seconds=120 --config-file=/home/ubuntu/fuse_connection.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o allow_other
```
### Guest machine specs:
* 1 vCPU
* 3 GB RAM
* 1 GB SWAP
* 14 GB for root partition (10 GB available)

FTP daemon "vsftpd" using mounted blob storage as home folder.
Video surveillance server, writes files chunks about 512MB once a hour over FTP server.
 
The problem begins from high RAM usage, then it consume almost all of swap file, and then sometimes it get to free some amount of swap, about 200MB, but eventually it end up at "blobfuse invoked oom-killer". Usually I've get used to reboot the whole system, insted of get it fixing by hands.

If needed I can provide more info or make some tests.

**Comment by amnguye** [comment]
Hi,

When blobfuse reads/writes to it, it caches the entire file. How big are the files are you writing to with the 512MB chunks? Considering you only allocated 1700MB to your ramdisk/cache tmp folder and if these files are bigger than that, that's why you might be hitting an out of memory issue. Also how many files are you writing/reading at once?

**Comment by yderi** [comment]
My apologies
I meant that the video surveillance system saves a stream, that is coming, into 512 MB file -s. It uploads one file per session (I can watch how the file is populated, by watching in parallel file size in a temp directory (tmpfs) and in blob storage). It uploads 48 files per 24 hours. So  I decided that ramdisk in 1700MB is enough to serve the needs of the video surveillance system. At least it enough to save/upload three files at once. The problem happens irregularly, once a week or a few weeks. I guess that it might be a cache timeout or other parameters. Last few weeks, it hits the problem more often. It doesn't matter if you increase the page file, it uses almost all of it and eventually hit the OOM-Killer. 
Should I use log level - debug ?

**Comment by amnguye** [comment]
Hi,

So it doesn't upload one 512MB file every hour like you said in your original post, it uploads 2 512MB files every hour? I just wanted to confirm this.

I'm not sure how helpful using log level would be since you've already told me what you're doing. But yeah you can add "log-level=LOG_DEBUG" to your mount command and viewing the /var/log/syslog for any blobfuse outputs or any outputs related to this issue may help.

It also might be a problem with this being a persisting mount as well. We are actually well aware of the caching problem blobfuse has, and to workaround this problem it would require you to unmount blobfuse and remount. Which leads me to my next question. If you only upload a file every hour, why do you need a persisting mount?

**Comment by yderi** [comment]
Hello Amanda,

Yes, it uploads approximately 2 x 512MB of every hour, but I never see, that uploads happen in parallel, only one by one (when the first channel finishes uploading a file,  only then the second channel start to upload). File upload itself takes no more than a few minutes. 

Switch log to debug level.

Do you mean, that blob storage cannot be permanently mounted by "blobfuse"? I need a permanently mounted BLOB storage to be ready for new uploads whenever the server needs it (server make own decision when it ready to upload a new portions of files).

**Comment by a139786** [comment]
Have you tried using —tmp-path on the root file system since you have 10GB available? Might be worth trying. I mean the rates you’re describing don’t sound like RAM is required for throughput.

Thanks and Regards,
Barry Anderson
(Security) Solution Architect, (Enterprise Splunk|Security Uplift Program)
m: +61 412 051 878
t : +61 3 8633 7217
e : barry.anderson@agl.com.au

________________________________

**Comment by amnguye** [comment]
So Barry's suggestion is correct, it would mitigate the issue and it would happen less often however eventually it would happen again with a persisting mount.

We already logged the issue here with the problem of constant memory usage. 
https://github.com/Azure/azure-storage-fuse/issues/246

So whenever your server makes the decision it needs to upload new portions of files (aka files of size 512MB), why doesn't it just mount blobfuse then after its done uploading the new files, it unmounts. Or is that something you cannot get the server to do?

**Comment by yderi** [comment]
I do not understand, how mounting temp directory to real FS (instead of ramdisk) will help to avoid memory consumption. Current consumption by ramdisk is 2 files by 512 MB and I can see that once it got uploaded to the blob it no longer stay in temp directory used by the ramdisk.
Client-side is a dumb server that only can upload files, there no way to make signaling, like "Hey server I will make upload files, be prepared (mount your blobfuse)"

To better understand the situation:
**dumb-clients** <---> **FTP server** (with blobfuse in backend). 
- Clients know nothing about blobfuse, they only know how to talk to the server using a simple FTP protocol. 
- FTP server also doesn't know about filesystem it is using for storing files, as it looks like a regular filesystem for them. Also, the server doesn't know when a new connection will be initiated by the client-side.

Is there any way to I can help to speed up a troubleshoot or catch what cause the problem with high memory usage? Is it looks like a memory leak?

**Comment by a139786** [comment]
I don’t mean to sound insulting with this question, but do you understand what a ramdisk is? A ramdisk is a filesystem mounted against memory, so everything you put in a ramdisk is stored in memory which means two things:
(A) it’s fast - *very* fast;
(B) every object you store in the ramdisk takes its size in memory away from the free system ram (this is not 100% true as your ramdisk may use compression but that then takes away from (A) so typically not.

So if you have a memory mounted /tmp (and your blob-fuse cache dir is there) *and* you’re using a ramdisk, that means you potentially have two copies of the file *in memory* at the same time. This is of course fine in you have 1T of ram and 1M files, but not so much if you have 2G of ram and 1G files. I hope this explanation helps.

Next Action: (None required; informational only.)

Thanks and Regards,
Barry Anderson
Solution Architect, Security Uplift Program
m: +61 412 051 878

e : barry.anderson@agl.com.au

________________________________
