### ISSUE TITLE
Blobfuse permission issues ??? and unmounts in a few days

### ISSUE THREAD

**Issue by vyelamanchili** [Azure/azure-storage-fuse#310]
### Which version of the blobfuse was used?

1.0.3 (upgraded to 1.1.1 but still blobfuse --version shows 1.0.3)

### Which OS (please include version) are you using?

Ubuntu Xenial (16.04)

### What problem was encountered?

Creating this new one with all details of my issues: Follow up from [Here ](https://github.com/Azure/azure-storage-fuse/issues/246#issuecomment-525975888)

1. blobfuse folder permission issue : After hours of troubleshooting and mounting the azure container using blobfuse successully **using a user that apache runs on** (i.e. appserviceuser) so that apache can read and write to this folder on one of my drupal "files" folder, I started seeing ???? in permissions of the folder that was mounted. 
![image](https://user-images.githubusercontent.com/4511025/63959158-8db72180-ca59-11e9-9fd1-aa158f2534dd.png)

I ignore this in the beginning because site was running fine for a while with these permissions but then a couple of days later the site started having cache write issues to that folder which broke the site and loaded it as a text site.

2. On another instance of the blobfuse on another drupal site that I setup, the images were not loading after a couple of days of running and I figured out that the blobfuse mounted folder was unmounted. I want to know how to keep track of this unmountig when it happens (probably some unix tool or script that can help monitor it like Monit?) and then remount the blobfuse container using fstab as mentioned in the documentation ([documented ](https://github.com/Azure/azure-storage-fuse/wiki/2.-Configuring-and-Running#persisting) steps didnt work for me)

### Have you found a mitigation/solution?

- Unmounting using fusermount -u [folder]
- Clearing the temporary .htaccess, css and js files that the drupal site creates immediately after unmounting if apache is running.
- remounting containers using blobfuse manually which wont be an acceptable solution for our production sites.

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?

Nothing useful for these issues 

### If relevant, please share your mount command.

sudo as _appserviceuser_ then do the following 

`blobfuse /data/sitename/files --tmp-path=/mnt/resource/blobfusetmp/sitename/files --config-file=/data/blob_config/fuse_sitename_files.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 **-o allow_root**`

have used this for testing also logged in as me on the server (I need the files to be written and readable by _appserviceuser_ account not mine)

`**sudo** blobfuse /data/sitename/files --tmp-path=/mnt/resource/blobfusetmp/sitename/files --config-file=/data/blob_config/fuse_sitename_files.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 **-o allow_root**`

and tried this too logged in as _appserviceuser_

`blobfuse /data/sitename/files --tmp-path=/mnt/resource/blobfusetmp/sitename/files --config-file=/data/blob_config/fuse_sitename_files.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 
`

**Comment by amnguye** [comment]
1. Usually those question marks go away after you've unmounted and mounted the filesystem again. We're still looking into why this is happening. In any case, please make sure your user is the owner of the mounted directory and you allowed you allow everyone to read and execute the directory, and the file owner is allowed to write to the file as well (e.g. chmod 755).

2. I am not sure what to recommend to you in the case to have some other script alert you when blobfuse unmounts randomly and to remount when it does happen. You could possibly use cron to schedule a unmount and remount in order to ensure that you clear the cache periodically. I have personally not used cron or monit yet. But they seem like good options if this is what you want to achieve.

You will have to give more insight into why fstab does not work for you.

I will reiterate again since I'm assuming the upgrade did not work out. If it's getting unmounted randomly, I will suspect it is running out of memory for how much you've allocated to it.

**Comment by vyelamanchili** [comment]
> 1. Usually those question marks go away after you've unmounted and mounted the filesystem again. We're still looking into why this is happening. In any case, please make sure your user is the owner of the mounted directory and you allowed you allow everyone to read and execute the directory, and the file owner is allowed to write to the file as well (e.g. chmod 755).

I have unmounted and mounted back several times and the ?? still shows up. Even though I setup the owner of the mounting folder to be the Apache user ,that is going to read and write to that folder, it still keeps changing ownership randomly and at some points shows ??s

> 2. I am not sure what to recommend to you in the case to have some other script alert you when blobfuse unmounts randomly and to remount when it does happen. You could possibly use cron to schedule a unmount and remount in order to ensure that you clear the cache periodically. I have personally not used cron or monit yet. But they seem like good options if this is what you want to achieve.

I will try cron and monit and will update here if I am able to successfully set them up.

> I will reiterate again since I'm assuming the upgrade did not work out. If it's getting unmounted randomly, I will suspect it is running out of memory for how much you've allocated to it.

So I ran update blobfuse and it said successfully installed 1.1.1 but when I ran blobfuse --version it gave me 1.0.3 . I even restarted the server to see if it would fix the version update issue. I was wondering if the version number for some reason was not changed in the app code itself, if applicable?

**Comment by NaraVen** [comment]
@vyelamanchili , Please download the latest version 1.3.4. It is published for Ubuntu. We do not see those errors anymore even when we specify -o allow_root. It is difficult to debug older version so I am closing this issue. Feel free to reopen if you are still blocked.

**Comment by datalifenyc** [comment]
Storage Type: Azure Data Lake Storage Gen2 - Blob Container
Compute: Data Science VM
Application: RStudio

Unfortunately, the issue still exists in blobfuse 1.4.1. The optional parameter, `-o allow_root` will not resolve the issue because root already has access to the mounted files. My current working **solution** is to add `-o allow_other` in the `sudo blobfuse...` command. This will give your current user and other users access (_not exactly the behavior I was looking for, but good enough for now_) access to the directory that will contain the mounted blob storage.

There are a lot of references to this issue, but I would recommend the following as a guide:

[BlobFuse - A Microsoft supported Azure Storage FUSE driver](https://github.com/Azure/azure-storage-fuse)
- The GitHub repo for blobfuse.

[How to mount Blob storage as a file system with blobfuse](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-how-to-mount-container-linux)
- Microsoft's documentation on mounting blob storage using blobfuse. 
- Use the _timeout_ options provided in the Mount section.
- This is where I found the hint to use `-o allow_other`.

[Question marks showing in ls of directory. IO errors too](https://serverfault.com/questions/65616/question-marks-showing-in-ls-of-directory-io-errors-too)
Unfortunately, this did not resolve the folder permissions issue, but it helped me better understand what was going on.

[How to mount Azure Blob Storage inside a Linux machine](https://public-wiki.iucc.ac.il/index.php/How_to_mount_Azure_Blob_Storage_inside_a_Linux_machine)
- This is the cleanest step-by-step example I have found. Unfortunately, it will not resolve the folder permissions issue.

Summary:
Add `-o allow_other` in the `sudo blobfuse...` command. 

The folder permission issue occurs in the mount step: `blobfuse...`. Prior to that you will have full access to the created folders, assuming you changed permissions using `chown` or `chmod`. Unfortunately, recursively adding `chomd +x /<your-path-to_folder>` will not resolve this issue.

**Comment by vibhansa-msft** [comment]
Can you share your complete mount command and config file. For gen2 account you need to pass an extra argument to mount command "--use-adls=true". Also as its gen-2 account you shall not pass allow_other or allow_root, as blobfuse will return permissions based on the ACLs set on actual blob.
