### ISSUE TITLE
blobfuse 1.1.1 for linux 6 

### ISSUE THREAD

**Issue by imlight** [Azure/azure-storage-fuse#327]
Hello Team, 

I cound't find blobfuse 1.1.1 for enterprise linux 6 . Can you please confirm ?

I getting  blob-fuse process core dumping 

```
Nov 11 11:58:07 mirror abrtd: Directory 'ccpp-2019-11-11-11:58:07-9739' creation detected
Nov 11 11:58:07 mirror abrt[12943]: Saved core dump of pid 9739 (/usr/bin/blobfuse) to /var/spool/abrt/ccpp-2019-11-11-11:58:07-9739 (56479744 bytes)
Nov 11 11:58:07 mirror abrtd: Package 'blobfuse' isn't signed with proper key
Nov 11 11:58:07 mirror abrtd: 'post-create' on '/var/spool/abrt/ccpp-2019-11-11-11:58:07-9739' exited with 1
Nov 11 11:58:07 mirror abrtd: Deleting problem directory '/var/spool/abrt/ccpp-2019-11-11-11:58:07-9739'
```

Saw in 1.1.1 release segfault issue was addressed , was thinking to give upgrade and see if that helps.

**Comment by amnguye** [comment]
Hi Prakash,

Just to clarify, are you talking about Red Hat Enterprise Linux 6? Did you try installing the binary from our releases page?

Is this log you are pasting in reference to the problem you are having with blobfuse and think that the fix for the segmentation fault would help solve this problem as well? This log does not look similar to the original issue that reported the segmentation fault. I cannot determine what the problem is due to the lack of information.

Please follow the blobfuse github issue submission form so we can better understand the issue at hand.

**Comment by imlight** [comment]
Hi , 

Thanks for reply.

yes , Redhat Enterprise Linux 6 . We prefer if it is in RPM format. Installing binaries directly sometimes  gets little out of hand. 


re ```Is this log you are pasting in reference to the problem you are having with blobfuse and think that the fix for the segmentation fault would help solve this problem as well?```

Yes , From last few days It has happened multiple time , that blob mount has dropped.  We had to remount that.

It may be related to the number of files we are pushing and the high cpu load our server has , but few days ago this was working fine. 

I too thought segfault and core dump ( issue we see at our end ) issue might be different , and to rule out that wanted to see if the higher version will help resolve the issue.

**Comment by amnguye** [comment]
Could you please provide a syslog with anything pertaining to blobfuse to see what's happening before the seg fault happened? You would need to append the flag "--log-level=LOG_DEBUG" to the mount command.

Also could you provide your mount command?

**Comment by rishabpoh** [comment]
Please re-open this issue if it still persists.
