### ISSUE TITLE
Contribute: systemd file for blobfuse using access key

### ISSUE THREAD

**Issue by scegg** [Azure/azure-storage-fuse#347]
Hi.

I wrote a systemd config file for blobfuse but I don't know where to upload it in this code structure. Please, if you accept, move this code to the folder you want.

This file should be placed in `/etc/systemd/system`, name could be `blobfuse.service` or others you like. 5 Environment lines should be modified before saving.

```[Unit]
Description=Blobfuse
After=network.target

[Service]
Environment=BlobMountingPoint=<path/to/the/mounting/point>
Environment=BlobTmp=<path/to/the/temp/folder>
Environment=AZURE_STORAGE_ACCOUNT=<account.name>
Environment=AZURE_STORAGE_ACCESS_KEY=<account.key>
Environment=ContainerName=<container.name>
Type=forking
ExecStart=/usr/bin/blobfuse ${BlobMountingPoint} --container-name=${ContainerName} --tmp-path=${BlobTmp} -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o allow_other
ExecStop=/usr/bin/fusermount -u ${BlobMountingPoint}

[Install]
WantedBy=multi-user.target```

**Comment by amnguye** [comment]
Hi,

Thanks for your contribution.

I think there needs to be a few more changes to this file if we want to be considered to be merged in. For example there are more options how users can access their storage account, like using their sas token or by using the msi oauth. Also the mount command will need to not have those default options and users should be able to set those themselves. This would remove some user error.

In terms of where this file should be placed, it should just probably be put in the main directory due to the user having to move it to their '/etc/systemd/system' directory anyways. This file shouldn't block any of the source. 

There probably needs to be something added to our README as well to better help people use this as well.

**Comment by scegg** [comment]
Yes, you are right. Environment variables starting with `AZURE_` could be added in the service block. Edit this piece as you wish. This project, as well as this issue, is under MIT.

**Comment by scegg** [comment]
FYI: 2 versions of systemd service files are ready for merging.
