### ISSUE TITLE
Blob random disconnection 

### ISSUE THREAD

**Issue by quatrecentun** [Azure/azure-storage-fuse#349]
### Which version of the blobfuse was used?
Lastest, blobfuse 1.1.1

### Which OS (please include version) are you using?
CentOS Linux release 7.6.1810

### What problem was encountered?
We have a blobfuse mount point on a server and we observe since couple weeks some random disconnect of the mount point on our supervision solution.
This is a problem because we use this mountpoint 24/7 so everytimes there is a disconnect, there are file read errors...
Do you think blobfuse is a good way for use 24/7 ?

Thanks in advance

### Have you found a mitigation/solution?
Nop.

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
Dec 30 10:08:04 XXXXXX blobfuse[1443]: list_blobs_hierarchical failed for the 1 time with errno = 400.
Dec 30 10:19:25 XXXXXX  blobfuse[1443]: Attempt at parsing XML response failed. Unable to parse "Error" from storage_error
Dec 30 10:19:55 XXXXXX blobfuse[1443]: list_blobs_hierarchical failed for the 1 time with errno = 400.

### If relevant, please share your mount command.
blobfuse /storage-blob/xxx --tmp-path=/mnt/resource/blobfusetmp --log-level=LOG_WARNING --config-file=/storage/xxx/fuse_connection_ope.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o uid=48 -o gid=48 -o allow_other

**Comment by amnguye** [comment]
Hi,

For the syslog errors you've received, are those blobfuse outputs constantly repeating? Like the message "attempt at parsing XML response failed"? Then the "list_blobs_hierarchical failed" afterwards?

There could be two things that are happening, it could be that the cache is filling up and not being cleared out due to the 24/7 mountpoint. Or if you're making a lot of changes in the mounted container, you could be throttling the storage account as well.

This is has been an ongoing issue for blobfuse.

**Comment by quatrecentun** [comment]
Hi,

The error _"...time with errno = 400."_ it's repeated about 20 times a day. And sometimes I see that error : 
_Dec 28 22:10:58 xxxxx kernel: blobfuse[13507]: segfault at 30 ip 0000000000452d64 sp 00007f62c4fcbdd0 error 4 in blobfuse (deleted)[400000+c8000]_

After searching I found that error was resolved after updating blobfuse to lastest version. What I've done... And still get the same.

For the error _"parsing XML response failed"_ I only see it very rarely on logs.

About the cache, how can I clean it ? And what impact will this have on the storage ?
What do you mean by an ongoing issue for blobfuse ?

Thanks for your help.

**Comment by amnguye** [comment]
Hi,

That does look similar to the seg fault issue we attempted to fix in the latest version. Considering that the error message "Attempt at parsing XML response failed" appears in your logs, it looks like blobfuse was able to avoid some seg faults but not all considering that it still seg faulted for you, but it looks like it seg faulted in a similar area.

I think the issue may be that your storage account may be getting throttled due to constantly hitting the storage account. It may also explain why the xml response is consistently coming back formatted incorrectly from what blobfuse expects and thats why you're seeing seg fault messages and "Attempt at parsing XML response failed".

I will mark this issue as a bug for now and we will look into making sure the seg faults are handled more gracefully when XML responses come back unformatted and/or formatted in a way that blobfuse does not expect.

For clearing the cache, considering you're doing transactions consistently with blobfuse, I recommended unmounting and remounting blobfuse to fully clear the cache. However I think that the issue may not be due to the cache filling up now that you mention the seg fault. This will not have an impact on the storage container.

When you say its repeated 20 times a day, does that mean that eventually blobfuse gains connection again and you stop seeing the problem eventually. Or do you unmount and remount blobfuse?

**Comment by quatrecentun** [comment]
Hi,

Thanks for your answer, I will try your advice of unmount and remount the blobfuse for clearing the cache, even if you think it's not the solution, we'll be fixed.

I failed to identify a common cause that could explain this problem for now but I'm searching...
I ask to our client to report us when he see the blobfuse unmounted.

About your question, normly the blobfuse is mounted 24/7 but the only solution we have for now is to reboot the VM or unmout/mount the blob when we detect errors on it.

**Comment by quatrecentun** [comment]
Hi,

Since few days we didn't found other disconnexion !
So you can close the issue I think :)

**Comment by amnguye** [comment]
Hi,

I still think this is a concerning issue that we are not catching **every** fault when parsing an incorrectly formatted XML response. So I will leave this issue open for now.

Thanks for finding the issue :)

**Comment by amnguye** [comment]
This is related to this PR #302 

@NaraVen Could you take a look at this? This is more related to the cpplite xml parsing, and making sure we handle errors there properly.

**Comment by vibhansa-msft** [comment]
Are you still facing this issue ? If so, can you try out the latest code base or version 1.3.3.

**Comment by NaraVen** [comment]
There was an encoding issue that could have caused this error 400 in earlier releases between Nov 2019 and Aug 2020. 1.3.4 has individually addressed all encoding issues. Hence, I am closing this one.
