### ISSUE TITLE
Able to read, but writing gets hung and after a few minutes file is still not in fused mountpoint or Azure

### ISSUE THREAD

**Issue by rgshareholder** [Azure/azure-storage-fuse#368]
### Which version of the blobfuse was used?
1.1.1

### Which OS (please include version) are you using?
Docker, RHEL 7 as host OS.

### What problem was encountered?
Copying a small sample text file or simply echoing into the mountpoint has no effect. Command appears stuck for several minutes, after which the shell is returned and when listing the files in the mount point the new files is not there (also not in Azure Blob storage - checked via the web UI). 

I'm able to view existing blobs (uploaded, e.g., via the Azure UI) locally in the fused mount point and copy them to another local directory from the fused mount.

### Have you found a mitigation/solution?
Yes. After mounting  (blobfuse), I need to run chown <user> on all the existing files in the mountpoint (= Azure container) in order to be able to get writes to work.

### If relevant, please share your mount command.
docker run -it --cap-add SYS_ADMIN --device /dev/fuse blobaccess
blobfuse /blobs --container-name=modelexelogs --tmp-path=/mnt/blobfusetmp

/blobs and /mnt/blobfusetmp have full write/read access.

**Comment by rgshareholder** [comment]
Upon further diagnosis, write permissions weren't set. If I can suggest, please add additional/proper error handler for such instance of user error :)

**Comment by rgshareholder** [comment]
Additional info - I'm able to create a directory within the mountpoint and write into it without issue (reflected in Azure), so the issue seems isolated to writing to base container directory.

**Comment by amnguye** [comment]
Hi,

Thanks for submitting this issue.

I agree that blobfuse should have given you an error back saying that it could not write a file to that directory because it does not have access to it. Because the mountpoint is so close to the root, I suspect that blobfuse got stuck trying to see if you had access to the mountpoint and hung. That's why it makes sense that when you ran chown on the mountpoint it started working. It also aligns with when you made the directory, it let you make files within that directory because as the user who created the directory, and through blobfuse we automatically give you full write/read access to that directory you just created.

Maybe another mitigation instead of running chown on all existing files in the mountpoint, is to run chown on the mount point itself (e.g. sudo chown <user> /blobs, maybe also use the -R for recursive)

Could you check the syslog and see if there was any error outputted there?

I will also label this as a bug and attempt to reproduce the error myself.

**Comment by NaraVen** [comment]
> Additional info - I'm able to create a directory within the mountpoint and write into it without issue (reflected in Azure), so the issue seems isolated to writing to base container directory.

Could you please mount blobfuse with one more commandline option  -o allow_other ?
Could you then share if you see the same issue.

**Comment by rishabpoh** [comment]
Please re-open this issue if it persists.
