### ISSUE TITLE
When using backslashes in path, directory creation fails with "No such file or directory"

### ISSUE THREAD

**Issue by wchill** [Azure/azure-storage-fuse#438]
### Which version of the blobfuse was used?
1.2.3, 1.2.4

### Which OS (please include version) are you using?
Ubuntu 16.04 (kernel 4.15.0), Ubuntu 20.04 (kernel 5.4.0)

### What problem was encountered?
When attempting to create a directory using `mkdir -p` and a path that has backslashes, directory creation fails with "No such file or directory". Linux does handle this correctly if creating in a directory not backed by blobfuse.

### Have you found a mitigation/solution?
Downgrade to 1.1.1 (it handles this correctly), or convert everything to forward slashes.

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
Unfortunately this was encountered in a docker container without a syslog daemon.

### If relevant, please share your mount command.
```bash
blobfuse /mnt/blobstorage/mount --tmp-path=/mnt/blobstorage/cache --file-cache-timeout-in-seconds=1000000 -o nonempty -o allow_other --config-file=/mnt/blobstorage/blobstore.cfg --log-level=LOG_WARNING
```

**Comment by vibhansa-msft** [comment]
Kindly paste your 'mkdir -p' command here, it will help us root-cause the issue.

**Comment by wchill** [comment]
`mkdir -p /mnt/workspaceblobstore/d\\a\\1\\s\\src\\PythonTests`

**Comment by vibhansa-msft** [comment]
What is the expectation here. As you have mentioned 1.1.1 converts '\' to '/' then 'd\\a' is no-longer a directory name, rather it represents 'd' as directory and 'a' as sub-directory. You want to create a directory 'd\\a' or 'a' as sub-directory. Current implementation is creating the sub-directory structure. Only problem may be the error throwing part, which I will investigate.

**Comment by vibhansa-msft** [comment]
Also in linux the same mkdir creates a directory with name 'd\\a' and not a sub-directory structure.

**Comment by NaraVen** [comment]
As per the Azure blob naming documentation: https://docs.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata it is a good practice to avoid backslashes.
Since directory is virtual in blob ( see below for details, you can still have the mkdir path mentioned below as a blob name , your mounted dir may look like a typical file structure though.
The Blob service is based on a flat storage scheme, not a hierarchical scheme. However, you may specify a character or string delimiter within a blob name to create a virtual hierarchy. For example, the following list shows valid and unique blob names. Notice that a string can be valid as both a blob name and as a virtual directory name in the same container:

/a

/a.txt

/a/b

/a/b.txt

You can take advantage of the delimiter character when enumerating blobs.

**Comment by vibhansa-msft** [comment]
Blobfuse will now replace '\\' with '/' and file/directories will be created accordingly. Bug fix is checked in, will be part of next release.
