### ISSUE TITLE
df shows same disk space stats for blobfuse mount as the blobfuse temp dir mount

### ISSUE THREAD

**Issue by yonisade** [Azure/azure-storage-fuse#543]
### Which version of the blobfuse was used?
1.0.2

### Which OS (please include version) are you using?
"Red Hat Enterprise Linux Server"
VERSION="7.9 (Maipo)"

### What problem was encountered?
I worry about free space available for writes.

df command shows the same storage stats (total/used/available space) for blobfuse mount as the mount in which the blobfuse temp dir resides:
**Filesystem      Size  Used Avail Use% Mounted on**
devtmpfs         16G     0   16G   0% /dev
tmpfs            16G     0   16G   0% /dev/shm
tmpfs            16G   26M   16G   1% /run
tmpfs            16G     0   16G   0% /sys/fs/cgroup
/dev/sda2       128G   22G  107G  17% /
**/dev/sdd         64G   24G   41G  37% /u01**   (_**/u01/blobfusetmp**_ is inside)
/dev/sda1       509M  356M  154M  70% /boot
**blobfuse         64G   24G   41G  37% /u02**

I understand that the available space represents the max file size that is possible to write there, but will the total size displayed limit processes ability to write any more data when the Used space reaches 64GB?

**Comment by vibhansa-msft** [comment]
Your observation is correct, 'df' on the mounted directory shows disk stats of the temp dir, this is by design. However this does not limit your storage container size by any means. File remains in temp directory only for a limited amount of time for local caching and then removed. Timeout is by default 120 seconds, and it can be configured by command line option "--file-cache-timeout-in-seconds".
