### ISSUE TITLE
Repo for RHEL 7 is out of date

### ISSUE THREAD

**Issue by pagienge** [Azure/azure-storage-fuse#557]
official documentation here

https://github.com/Azure/azure-storage-fuse/wiki/1.-Installation

Refers to this doc
https://docs.microsoft.com/en-us/windows-server/administration/Linux-Package-Repository-for-Microsoft-Software

When checking the official repo installed by those methods, the blobfuse version is out of date for RHEL 7 specifically:
https://packages.microsoft.com/rhel/7/prod/
blobfuse-1.0.2-rhel74.rpm                          11-May-2018 06:34

Other RHEL versions and other vendors seem to be up to date at 1.3.6,  other packages for RHEL7 are current also (see aadlinux)

**Comment by vibhansa-msft** [comment]
Due to some technical issues we are unable to update the Microsoft repos for past few releases. You need to download the RPM and install it manually. RPMs/Debs are available at below link :

https://github.com/Azure/azure-storage-fuse/releases/tag/blobfuse-1.3.6

As of now we do not release for RHEL7.4. If el7.5 is compatible you can try it out otherwise you need to clone the repo and build it locally.

**Comment by NaraVen** [comment]
@pagienge , We have published the latest blobfuse 1.3.6 to rhel 7, 7,2, 7.3, 7.5, and 7.8 also now
The version published for Rhel 7, 7,1, 7.3, and 7.5 are all built on RHEL 7.5. Please let us know if it does not work and then we will try building for RHEL 7.0.
