### ISSUE TITLE
Concurrent read same file throws exception

### ISSUE THREAD

**Issue by qjxu** [Azure/azure-storage-fuse#573]
### Which version of the blobfuse was used?
1.3.6

### What problem was encountered?
Simple code to spam multiple processes to access same file will easily repro above error. Got exception with PIL image.open().

Exception:
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    main()
  File "test.py", line 8, in main
    mp.spawn(main_worker, nprocs=gpus_per_node)
  File "/opt/conda/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/opt/conda/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/opt/conda/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 119, in join
    raise Exception(msg)
Exception:

-- Process 3 terminated with the following error:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/home/***/test.py", line 16, in main_worker
    im = Image.open(os.path.join(folder_full, f))
  File "/opt/conda/lib/python3.6/site-packages/PIL/Image.py", line 2862, in open
    "cannot identify image file %r" % (filename if filename else fp)
PIL.UnidentifiedImageError: cannot identify image file '/tmp/c/imagenet/2012/small/val/n01443537/ILSVRC2012_val_00049712.JPEG'

### Have you found a mitigation/solution?
Catch exception at file open and retry it.

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
Nope.

**Comment by vibhansa-msft** [comment]
Kindly share your mount command and syslog (with LOG_DEBUG).

**Comment by NaraVen** [comment]
@vibhansa-msft, I worked offline with this issue. It occurs when the files are not yet cached and is running in a multithreaded mode. I sent you the script to repro it via email. It appears to be a race condition issue when an open from one thread has downloaded an image file but the content is just syncing to the disk and another thread open the file locally since it is already downloaded but the bits of the image file is not completely synced to the disk. It happens in random files and when you run it again in multithreaded mode before the file-cache_timeout_in_seconds expires the error will not occur, every thing will work file.
The only way to repro it again is wait for file_cache_timeout_in_seconds to expire and rerun in multithreaded mode.
Best lines of code to repro this is the below python snippets.
val_loader = torch.utils.data.DataLoader(
    datasets.ImageFolder(valdir, transforms.Compose([
        transforms.Resize(256),
        transforms.CenterCrop(224),
        transforms.ToTensor(),
        normalize,
    ])),
    batch_size=64, shuffle=False,
    num_workers=4, pin_memory=True)


for i, (images, target) in enumerate(val_loader):
        print(str(time.ctime()))
        print(str(i))

**Comment by NaraVen** [comment]
worked offline with the client adding the below mount options to turn off symlinks prevented the race condition, closing this for now. 
--no-symlinks=true --use-attr-cache=true
