### ISSUE TITLE
Question/Feature Request: Check sync status for files and folders

### ISSUE THREAD

**Issue by ivanignatiev** [Azure/azure-storage-fuse#676]
Hello,

I have a similar question as posted on StackOverflow 6 months ago: https://stackoverflow.com/questions/67617735/getting-file-sync-status-in-blobfuse-azure-storage

Is there is any information like a flag or the latest sync date for files and folders?

Nowadays it is hard to determine if all files were fully uploaded to blob storage.

**Comment by vibhansa-msft** [comment]
@ivanignatiev What is the use-case you are looking for. Blobfuse does not have any flag to determine that files/folders are synced or not because when you open a file its downloaded on local disk and as soon as you flush/close the file its immediately uploaded to container. Based on file-size/network bandwidth/disk speed this upload/download may take some time. However while file is being uploaded, even if you try to read that file you will always get updated contents only as its being served from local cache.
If you are interested in checking whether file is uploaded or not, you can keep tracking your local disk cache directory. When file-cache-timeout is hit all the closed files are deleted from there. So any file that was written and closed, once it disappears from local disk-cache you can say its fully in sync. If you want to go for this kind of detection then you will need to keep your file-cache timeout low.

**Comment by ivanignatiev** [comment]
@vibhansa-msft thank you for answer !  The local file system check could be the solution for me. 

My case is that I have immutable infrastructure with an app on VM which is using blobfuse mounted folder. I am never sure when I can delete the VM to not loose the written data in blobfuse mounted folder.

**Comment by vibhansa-msft** [comment]
Understood your use case. You can keep file-cache-timeout to few seconds (5 seconds may be) and after application has done processing and closed all handles, just keep monitoring the local cache. Once its wiped out completely its safe to unmount.
If you do not wish to wait for this cool-down time, after application has closed all the handles it shall be safe to unmount.

**Comment by vibhansa-msft** [comment]
If this answers your question kindly close this issue. Feel free to reopen or ask any further queries on this.

**Comment by vibhansa-msft** [comment]
Closing this as there is no update. Feel free to reopen if you have any further queries on this.
