### ISSUE TITLE
Could not open file

### ISSUE THREAD

**Issue by jcramer** [Azure/azure-storage-fuse#69]
New to fuse here... How come after I run blobfuse and try to access a file in the mounted drive the file explorer in Ubuntu has a big red banner that says "Could not open the file..."?

I can see all the file via nautilus file explorer, but that's what happens when I try to access the files.

Thanks,
Jim

**Comment by seguler** [comment]
FUSE exports the filesystem to the userspace, and is only accessible by the user mounting it. Sounds like you mounted blobfuse with one user, and trying to access with another user.

I just tested nautilus, works, but the experience is terrible. Nautilus tries to open each file I have in the folder one by one.. I am not sure why it does that.. But blobfuse downloads the blob down to disk every time a file is opened. We do this for performance reasons, but due to this solutions like Nautilus browser does not work well.

**Comment by jcramer** [comment]
I am accessing it with the same user.  I failed to mention there is an error message that says: "Failed to open input stream for file". See screen capture below.

![screenshot from 2018-01-31 17-31-46](https://user-images.githubusercontent.com/988195/35651209-dfb1b454-06ac-11e8-9671-b26553d5b437.png)

**Comment by seguler** [comment]
Thanks @jcramer - meanwhile it was good that you brought this up. The performance of the nautilus browser is very poor with blobfuse since it opens all the files on by one even when browsing. We will need to address this in the future.

**Comment by AlexanderYukhanov** [comment]
"FUSE exports the filesystem to the userspace, and is only accessible by the user mounting it." it's not actually a complete true -) you can make it available to everybody by mounting as a root and providing "-o allow_other" mount option.
