### ISSUE TITLE
How to use stream object?

### ISSUE THREAD

**Issue by kesavkolla** [Azure/azure-storage-fuse#786]
I am reading the preview feature list and found in 2.0.0-preview.1 there is a support for **Read streaming**

How to use this feature in other programming languages? Today I use blobfuse mount and then use rust programming language to read the files. How can I get benefit of this streaming read?

**Comment by tasherif-msft** [comment]
Hi @kesavkolla you can use this feature in any programming language by simply opening opening the file and doing reads on it regardless of the language you use. In order to configure the Streaming feature please refer to 
https://github.com/Azure/azure-storage-fuse/blob/main/sampleStreamingConfig.yaml as a sample config file for your mount. Please note that currently streaming is only enabled for `read-only` mode on mount, so do make sure to pass `--read-only=true` when mounting.

Let me know if you have any further questions.

Tamer

**Comment by vibhansa-msft** [comment]
Closing this as there is no updates on thread. Feel free to reopen in case you have any further queries on this topic.
