### ISSUE TITLE
tar blobfuse directory failed due to "file changed"

### ISSUE THREAD

**Issue by wangGH73** [Azure/azure-storage-fuse#854]
I try to tar a directory that is mounted to my vm through blobfuse. I freeze my application during running tar, but I find my tar always failed as "file changed as we read it" 
I am wondering will blobfuse will update the metadata even if the application is not changing those files

**Comment by vibhansa-msft** [comment]
If your test case involves creating a tar file from mounted directory, then new file (.tar) is getting created in local cache first. Unless that is closed by the application (file handle close) it will not be uploaded to the container. Kindly share your mount command and config file. Also, you can enable log_debug and share your log file for us to investigate further.

**Comment by vibhansa-msft** [comment]
One possible reason for this might be on download the file creation and last modified time changes and if tar compares those times before it starts and as it reads the file then it may assume files have changed. These times are change as we downloaded the file in local cache on open and they will represent the time of download now.

We have some fixes related to such things in our next generation blobfuse. Can you give blobfuse2 (preview) a try? You can get the preview-2 binaries here: https://github.com/Azure/azure-storage-fuse/releases/tag/blobfuse2-2.0.0-preview2. Refer to our README to get started. Our team will be happy to help you on this. For easier migration from v1 to v2 we have a compatible command "blobfuse2 mountv1 <mount point> <legacy v1 cli options>" so that you don't need to change anything v2 will create compatible config on its own and mount.

**Comment by wangGH73** [comment]
thanks for the response. the blobfuse2 is working with my test. when will you release this version?

**Comment by vibhansa-msft** [comment]
Thanks for the confirmation @wangGH73. Blobfuse2 is in preview mode as of now, official GA is planned somewhere in oct-nov timeframe. However we do support the preview versions as well so you can use it and report back any issues/concerns/suggestion for it.

**Comment by vibhansa-msft** [comment]
As we are not taking up any major changes in blobfuse, I am closing this issue here. You can continue using Blobfuse2-preview binaries. It will be GAed in this calendar year. Feel free to post your concerns on this thread.
