### ISSUE TITLE
blobfuse v2 failed to mount by managed identity

### ISSUE THREAD

**Issue by cvvz** [Azure/azure-storage-fuse#900]
### Which version of the blobfuse was used?
blobfuse v2

### What problem was encountered?
blobfuse v2 failed to mount by MSI

### Have you found a mitigation/solution?
Blobfuse v1 can mount successfully

### If relevant, please share your mount command.
```shell
export AZURE_STORAGE_AUTH_TYPE=MSI
export AZURE_STORAGE_IDENTITY_OBJECT_ID=xxxx
export AZURE_STORAGE_ACCOUNT=xxxx
blobfuse2 mount /test --cancel-list-on-mount-seconds=0 --empty-dir-check=false --tmp-path=/tmp/test --container-name=test --pre-mount-validate=true --use-https=true
failed to mount : config error in azstorage [Application ID and Resource ID not provided]
```

**Comment by vibhansa-msft** [comment]
New SDKs do not support Object ID based authentication since by AAD design it isn't accepted on service side as an identifier for service principals. You need to fallback to using ApplicationID instead.

**Comment by vibhansa-msft** [comment]
Closing this as latest SDK do not have support for this.

**Comment by vibhansa-msft** [comment]
I remember we added a hack to support object-id based authentication in later releases. It shall work with MSI based authentication.

**Comment by XiaoYue2-22** [comment]
Hello @vibhansa-msft, thanks for your reply. our cx and us tested with object-id but failed with error : 
*** blobfuse2: A new version [2.1.1] is available. Consider upgrading to latest version for bug-fixes & new features. ***
Error: failed to initialize new pipeline [failed to authenticate credentials for azstorage]

So we turned to use 'appid' instead of 'object-id' and it works, could you help clarify why?
